### ISSUE TITLE
LangGraph library not compatible with checkpointer base

### ISSUE THREAD

**Issue by SellCXHarsha** [langchain-ai/langgraph#1302]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
async for event in graph.astream(initial_state, debug=True):
        if "__end__" not in event:
            logging.info(f"Event received: {json.dumps(event, default=str)}")
            yield event
```

### Error Message and Stack Trace (if applicable)

```shell
File "/usr/local/lib/python3.10/dist-packages/langgraph/graph/__init__.py", line 1, in <module>
    from langgraph.graph.graph import END, Graph
  File "/usr/local/lib/python3.10/dist-packages/langgraph/graph/graph.py", line 26, in <module>
    from langgraph.channels.ephemeral_value import EphemeralValue
  File "/usr/local/lib/python3.10/dist-packages/langgraph/channels/__init__.py", line 1, in <module>
    from langgraph.channels.binop import BinaryOperatorAggregate
  File "/usr/local/lib/python3.10/dist-packages/langgraph/channels/binop.py", line 6, in <module>
    from langgraph.channels.base import BaseChannel, EmptyChannelError, Value
  File "/usr/local/lib/python3.10/dist-packages/langgraph/channels/base.py", line 17, in <module>
    from langgraph.checkpoint.base import Checkpoint
  File "/usr/local/lib/python3.10/dist-packages/langgraph/checkpoint/__init__.py", line 1, in <module>
    from langgraph.checkpoint.base import (
ImportError: cannot import name 'CheckpointAt' from 'langgraph.checkpoint.base' (/usr/local/lib/python3.10/dist-packages/langgraph/checkpoint/base/__init__.py)
```

### Description

Im not sure hyw this is not working

### System Info

langgraph==0.2.0
langgraph-checkpoint==1.0.2
langgraph-checkpoint-postgres==1.0.3
langgraph-checkpoint-sqlite==1.0.0

**Comment by vbarda** [comment]
you need to update to langgraph 0.2.3

**Comment by vbarda** [comment]
let me know if you're still facing the issue after updating!

**Comment by SellCXHarsha** [comment]
Hi, I am still facing the same issue.. it did not change the error unfortunately

**Comment by vbarda** [comment]
@SellCXHarsha could you please provide full code snippet with minimal reproducible example for the error?

**Comment by SellCXHarsha** [comment]
from langgraph.graph import StateGraph, END
it fails on this line when i upgrade to langgraph 0.2.3

**Comment by isahers1** [comment]
This is working fine for me - can you send me the entire error trace?

**Comment by SellCXHarsha** [comment]
harsha@harsha-Sword-15-A12UE:~/SellCX/Sandbox/api$ /bin/python3 /home/harsha/SellCX/Sandbox/api/Aysnc_Multi_Agent/ProCotAgent/proCoT_agent.py
Traceback (most recent call last):
  File "/home/harsha/SellCX/Sandbox/api/Aysnc_Multi_Agent/ProCotAgent/proCoT_agent.py", line 7, in <module>
    from langgraph.graph import StateGraph, END, START
  File "/usr/local/lib/python3.10/dist-packages/langgraph/graph/__init__.py", line 1, in <module>
    from langgraph.graph.graph import END, Graph
  File "/usr/local/lib/python3.10/dist-packages/langgraph/graph/graph.py", line 26, in <module>
    from langgraph.channels.ephemeral_value import EphemeralValue
  File "/usr/local/lib/python3.10/dist-packages/langgraph/channels/__init__.py", line 1, in <module>
    from langgraph.channels.binop import BinaryOperatorAggregate
  File "/usr/local/lib/python3.10/dist-packages/langgraph/channels/binop.py", line 6, in <module>
    from langgraph.channels.base import BaseChannel, EmptyChannelError, Value
  File "/usr/local/lib/python3.10/dist-packages/langgraph/channels/base.py", line 17, in <module>
    from langgraph.checkpoint.base import Checkpoint
  File "/usr/local/lib/python3.10/dist-packages/langgraph/checkpoint/__init__.py", line 1, in <module>
    from langgraph.checkpoint.base import (
ImportError: cannot import name 'CheckpointAt' from 'langgraph.checkpoint.base' (/usr/local/lib/python3.10/dist-packages/langgraph/checkpoint/base/__init__.py) 

and the versioning: 
langgraph==0.2.3
langgraph-checkpoint==1.0.2
langgraph-checkpoint-postgres==1.0.3
langgraph-checkpoint-sqlite==1.0.0

**Comment by isahers1** [comment]
Thank you, looking into it now

**Comment by isahers1** [comment]
Hmm I don't see a `CheckpointAt` import anywhere in `LangGraph.checkpoint.base`, could you maybe try uninstalling and then reinstalling the packages and trying again? Lmk if that doesn't work.

**Comment by vbarda** [comment]
@SellCXHarsha please let us know if re-installing the package from scratch fixes the issue!

**Comment by nfcampos** [comment]
Closing due to inactivity

**Comment by nitin-lamba-ck** [comment]
FWIW, `CheckpointAt` was used in opengpts repo [here](https://github.com/langchain-ai/opengpts/blob/541ae6f7f1e740662eb783f22677c9ba1e36a5a9/backend/app/checkpoint.py#L10C5-L10C17); also available in [docs](https://api.python.langchain.com/en/latest/_modules/langgraph/checkpoint/base.html) from a simple google search!

However, it was probably removed, so older code breaks if `langgraph` is upgraded. Not sure what the equivalent migration code looks like...

**Comment by Eliandrotg** [comment]
is thee a solution for this?

**Comment by nitin-lamba-ck** [comment]
We landed-up abandoning the older checkpoint code in openGPTs, and upgraded to using `AsyncPostgresSaver`. It came with it's own challenges - needing a patch in langgraph to fix type-checking failures in `ConfigurableFieldSpec`. Debugging this is painful due to so many moving parts and fast-changing interfaces...😢 

Following is our working dependency environment:

```
langchain = "^0.2.16"
langgraph = "^0.2.39" # 0.1.19
langgraph-checkpoint = "^2.0.2"
langgraph-checkpoint-postgres = "^2.0.2"
pydantic = "<2.0"
langchain-core = "^0.2.41"
```

**Comment by Eliandrotg** [comment]
@nitin-lamba-ck - we had a custom RedisCheckpoint (class RedisCheckpoint(BaseCheckpointSaver):
and using like such  CHECKPOINTER = RedisCheckpoint( at = CheckpointAt.END_OF_STEP)  but now because CheckpointAt enum doesnt exist my chat bot breaks .

**Comment by nitin-lamba-ck** [comment]
Yes, I did change the native langgraph library to get past the error (lot of debugging time to isolate the problem).

From the latest checkpoint packages, I don't see officially/ community supported library for **Redis**; only **sqlite**, **postgres** and **duckdb** are available. So, unfortunately, you may have to re-implement that custom RedisCheckpoint using the latest 2.0.x version.

FWIW, here's a MongoDB pattern ([checkpoint.py](https://github.com/mongodb-developer/hr_agentic_chatbot/blob/main/mongodb/checkpointer.py)) without using those older enums.

Good luck!

**Comment by Eliandrotg** [comment]
thank you so much - good pointers and have something to base my notions on now.

**Comment by yadgire7** [comment]
> you need to update to langgraph 0.2.3

library versions:
langchain                 0.2.17
langchain-anthropic       0.1.13
langchain-core            0.2.43
langchain-openai          0.1.7
langchain-text-splitters  0.2.4
langgraph                 0.2.69
langgraph-checkpoint      2.0.10
langgraph-sdk             0.1.51
langsmith                 0.1.147

**Comment by nitin-lamba-ck** [comment]
FWIW, another project (OpenGPT) had a recent commit last week to upgrade, and [this checkpoint code in 2cf3bf7](https://github.com/langchain-ai/opengpts/commit/2cf3bf75e11eecbbf3ae4c04a0f73f6ac5d9d6ec#diff-d9ce2f9c75e40cea9b6804b0ff7554a8bd11b76e008ec3f910963f288e5af1f6) is a good reference to update your old code to the new version.

Good luck!
