### ISSUE TITLE
langgraph-cli build fails on pip install  with "No .egg-info directory found"

### ISSUE THREAD

**Issue by godojoai** [langchain-ai/langgraph#1308]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [ ] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
$ langgraph build -c langgraph.json -t latest

langgraph.json:

{
    "dependencies": [
        "."
    ],
    "graphs": {
        "myagent": "./path/to/agent.py:graph",
    },
    "env": "./.env",
    "python_version": "3.12"
}


I have a requirements.txt file.

I have a Dockerfile that builds OK with this requirements.txt.
```

### Error Message and Stack Trace (if applicable)

```shell
- Pulling...+ docker pull langchain/langgraph-api:3.12
| Pulling...3.12: Pulling from langchain/langgraph-api
4f4fb700ef54: Pulling fs layer
262a5f25eec7: Pulling fs layer
ba32bf0f91fc: Pulling fs layer
1dc5ee30d1f7: Pulling fs layer
05f4007f5a88: Pulling fs layer
cb8d7ef7003a: Pulling fs layer
489bc8fee3cf: Pulling fs layer
8dfcd0f4e008: Pulling fs layer
af4ac4ecdac2: Pulling fs layer
5bb783acb057: Pulling fs layer
664fc557737b: Pulling fs layer
01c312566e6a: Pulling fs layer
/ Pulling...01c312566e6a: Download complete
- Pulling...05f4007f5a88: Download complete
8dfcd0f4e008: Download complete
\ Pulling...664fc557737b: Download complete
| Pulling...4f4fb700ef54: Download complete
/ Pulling...af4ac4ecdac2: Download complete
- Pulling...489bc8fee3cf: Download complete
/ Pulling...cb8d7ef7003a: Download complete
- Pulling...ba32bf0f91fc: Download complete
/ Pulling...1dc5ee30d1f7: Download complete
/ Pulling...5bb783acb057: Download complete
| Pulling...262a5f25eec7: Download complete
- Pulling...Digest: sha256:6b7b13f0c83d50ef83da8329f913ace3e3044ec11c1068201abb26551f525927
Status: Downloaded newer image for langchain/langgraph-api:3.12
docker.io/langchain/langgraph-api:3.12
+ docker build -f - -t latest /Users/user/developer/myproject <
FROM langchain/langgraph-api:3.12
ADD . /deps/myproject
RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*
ENV LANGSERVE_GRAPHS='{"marketer": "/deps/myproject/path/to/myagents.py:graph"}'
WORKDIR /deps/myproject
/ Building...#0 building with "desktop-linux" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 354B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/langchain/langgraph-api:3.12
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 transferring context: 181B done
#3 DONE 0.0s

#4 [1/4] FROM docker.io/langchain/langgraph-api:3.12@sha256:6b7b13f0c83d50ef83da8329f913ace3e3044ec11c1068201abb26551f525927
#4 resolve docker.io/langchain/langgraph-api:3.12@sha256:6b7b13f0c83d50ef83da8329f913ace3e3044ec11c1068201abb26551f525927 done
- Building...#4 DONE 0.1s

#5 [internal] load build context
#5 transferring context: 8.31MB 0.1s done
#5 DONE 0.1s

#6 [2/4] ADD . /deps/myproject
#6 DONE 0.1s
\ Building...
#7 [3/4] RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*
\ Building...#7 1.002 Obtaining file:///deps/myproject
/ Building...#7 1.003   Preparing metadata (setup.py): started
- Building...#7 1.315   Preparing metadata (setup.py): finished with status 'done'
\ Building...#7 1.400 ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-uxa0sfwa
#7 ERROR: process "/bin/sh -c PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*" did not complete successfully: exit code: 1
| Building...#0 building with "desktop-linux" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 354B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/langchain/langgraph-api:3.12
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 transferring context: 181B done
#3 DONE 0.0s

#4 [1/4] FROM docker.io/langchain/langgraph-api:3.12@sha256:6b7b13f0c83d50ef83da8329f913ace3e3044ec11c1068201abb26551f525927
#4 resolve docker.io/langchain/langgraph-api:3.12@sha256:6b7b13f0c83d50ef83da8329f913ace3e3044ec11c1068201abb26551f525927 done
#4 DONE 0.1s

#5 [internal] load build context
#5 transferring context: 8.31MB 0.1s done
#5 DONE 0.1s

#6 [2/4] ADD . /deps/myproject
#6 DONE 0.1s

#7 [3/4] RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*
#7 1.002 Obtaining file:///deps/myproject
#7 1.003   Preparing metadata (setup.py): started
#7 1.315   Preparing metadata (setup.py): finished with status 'done'
#7 1.400 ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-uxa0sfwa
#7 ERROR: process "/bin/sh -c PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*" did not complete successfully: exit code: 1
------
 > [3/4] RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*:
1.002 Obtaining file:///deps/myproject
1.003   Preparing metadata (setup.py): started
1.315   Preparing metadata (setup.py): finished with status 'done'
1.400 ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-uxa0sfwa
------
Dockerfile:7
--------------------
   5 |     ADD . /deps/myproject
   6 |     
   7 | >>> RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*
   8 |     
   9 |     ENV LANGSERVE_GRAPHS='{"myagent": "/deps/path/to/agent.py:graph"}'
--------------------
ERROR: failed to solve: process "/bin/sh -c PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/ryj0fu6muwqg9obxkd91iksy6
------
 > [3/4] RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*:
1.002 Obtaining file:///deps/myproject
1.003   Preparing metadata (setup.py): started
1.315   Preparing metadata (setup.py): finished with status 'done'
1.400 ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-uxa0sfwa
------
Dockerfile:7
--------------------
   5 |     ADD . /deps/myproject
   6 |     
   7 | >>> RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*
   8 |     
   9 |     ENV LANGSERVE_GRAPHS='{"myagent": "/deps/path/to/agent.py:graph"}'
--------------------
ERROR: failed to solve: process "/bin/sh -c PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/ryj0fu6muwqg9obxkd91iksy6
```

### Description

I'm trying to deploy my agent to LangGraph Cloud to test that service. My agent and code has been working great via Docker.

The error I'm getting doesn't really help me solve it.

### System Info

langchain==0.2.12
langchain-anthropic==0.1.22
langchain-cli==0.0.28
langchain-community==0.2.11
langchain-core==0.2.29
langchain-openai==0.1.21rc2
langchain-pinecone==0.1.3
langchain-text-splitters==0.2.2
langchainhub==0.1.20

Python 3.12.4
macOS 14.5 Sonoma

**Comment by vbarda** [comment]
@godojoai could you add `langgraph-cli` version as well to the system info?

**Comment by vbarda** [comment]
@godojoai are you using a setup.py file? if so, could you please provide it? also, could you provide your dockerfile as well?

**Comment by godojoai** [comment]
I am not using setup.py.

Here is the Dockerfile that works.

```
# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Update pip
RUN pip install --upgrade pip

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt --use-deprecated=legacy-resolver

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV PORT=80
ENV ASYNC=true
ENV LANGCHAIN_TRACING_V2=true

# Run uvicorn server when the container launches
CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "80"]
```

**Comment by godojoai** [comment]
Hangon. I did have an empty setup.py file in my dir.

After removing it I'm getting the following error:

```
ValueError: Package name 'src' used in local dep '.' is reserved. Rename the directory.
```

Can't I have my source code inside `src` folder? Any workaround?

**Comment by godojoai** [comment]
Hmm, I see.. I'm using a standard python dir structure with `src/<my-app>` structure instead of having `<my-app>` at the top-level.

I have the `requirements.txt` at the top-level.

So you're saying I need to move my requirements.txt to inside the `src/<my-app>` dir?

**Comment by vbarda** [comment]
> So you're saying I need to move my requirements.txt to inside the src/<my-app> dir?

that's correct

**Comment by godojoai** [comment]
Ok, I did the following changes and it now `langgraph up` doesn't work. See log from the api container:

```
2024-08-12 17:15:35 langgraph-api-1       | 2024-08-12T16:15:35.964831Z [info     ] Started server process [1]     [uvicorn.error] api_revision=c0d671e api_variant=licensed color_message=Started server process [%d] filename=server.py func_name=_serve lineno=82
2024-08-12 17:15:35 langgraph-api-1       | 2024-08-12T16:15:35.965112Z [info     ] Waiting for application startup. [uvicorn.error] api_revision=c0d671e api_variant=licensed filename=on.py func_name=startup lineno=48
2024-08-12 17:15:35 langgraph-api-1       | 2024-08-12T16:15:35.965601Z [warning  ] No license key found, running in test mode with LangSmith API key. For production use, set LANGGRAPH_CLOUD_LICENSE_KEY in environment. [langgraph_license.validation] api_revision=c0d671e api_variant=licensed filename=validation.py func_name=get_license_status lineno=80
2024-08-12 17:15:36 langgraph-api-1       | 2024-08-12T16:15:36.516144Z [info     ] HTTP Request: GET https://api.smith.langchain.com/auth?langgraph-api=true "HTTP/1.1 200 OK" [httpx] api_revision=c0d671e api_variant=licensed filename=_client.py func_name=_send_single_request lineno=1773
2024-08-12 17:15:36 langgraph-api-1       | 2024-08-12T16:15:36.854091Z [error    ] Traceback (most recent call last):
2024-08-12 17:15:36 langgraph-api-1       |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 732, in lifespan
2024-08-12 17:15:36 langgraph-api-1       |     async with self.lifespan_context(app) as maybe_state:
2024-08-12 17:15:36 langgraph-api-1       |   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
2024-08-12 17:15:36 langgraph-api-1       |     return await anext(self.gen)
2024-08-12 17:15:36 langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^
2024-08-12 17:15:36 langgraph-api-1       |   File "/api/langgraph_api/lifespan.py", line 21, in lifespan
2024-08-12 17:15:36 langgraph-api-1       |   File "/api/langgraph_api/shared/graph.py", line 117, in collect_graphs_from_env
2024-08-12 17:15:36 langgraph-api-1       |   File "/usr/local/lib/python3.12/site-packages/langchain_core/runnables/config.py", line 619, in run_in_executor
2024-08-12 17:15:36 langgraph-api-1       |     return await asyncio.get_running_loop().run_in_executor(
2024-08-12 17:15:36 langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-12 17:15:36 langgraph-api-1       |   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
2024-08-12 17:15:36 langgraph-api-1       |     result = self.fn(*self.args, **self.kwargs)
2024-08-12 17:15:36 langgraph-api-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-12 17:15:36 langgraph-api-1       |   File "/usr/local/lib/python3.12/site-packages/langchain_core/runnables/config.py", line 610, in wrapper
2024-08-12 17:15:36 langgraph-api-1       |     return func(*args, **kwargs)
2024-08-12 17:15:36 langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^
2024-08-12 17:15:36 langgraph-api-1       |   File "/api/langgraph_api/shared/graph.py", line 142, in _graph_from_spec
2024-08-12 17:15:36 langgraph-api-1       |   File "/api/langgraph_api/shared/graph.py", line 139, in _graph_from_spec
2024-08-12 17:15:36 langgraph-api-1       |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
2024-08-12 17:15:36 langgraph-api-1       |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2024-08-12 17:15:36 langgraph-api-1       |   File "/deps/__outer_myapp/myapp/agents/chat.py", line 17, in <module>
2024-08-12 17:15:36 langgraph-api-1       |     from .tools import analyze_positioning_from_urls_tool, search_tool
2024-08-12 17:15:36 langgraph-api-1       | ImportError: attempted relative import with no known parent package
2024-08-12 17:15:36 langgraph-api-1       | Could not import python module for graph: GraphSpec(id='marketer', path='/deps/__outer_myapp/myapp/agents/chat.py', module=None, variable='graph')
2024-08-12 17:15:36 langgraph-api-1       |  [uvicorn.error] api_revision=c0d671e api_variant=licensed filename=on.py func_name=send lineno=121
2024-08-12 17:15:36 langgraph-api-1       | 2024-08-12T16:15:36.854179Z [error    ] Application startup failed. Exiting. [uvicorn.error] api_revision=c0d671e api_variant=licensed filename=on.py func_name=startup lineno=59
```

**Comment by godojoai** [comment]
Ok fixed it. Moved my project to not use a src dir, but just moved the top-level module to the top-level dir.

Now works. Thanks.

**Comment by gbaian10** [comment]
So, assuming my source code is in the `src` directory, one approach is to wrap all the code in an additional outer directory.
Another approach is to rename the `src` folder?

**Comment by vbarda** [comment]
> So, assuming my source code is in the `src` directory, one approach is to wrap all the code in a directory under `src`. Another approach is to rename the `src` folder?

yup, that's correct
