### ISSUE TITLE
Get error returning list object as state update from nodes

### ISSUE THREAD

**Issue by Valdanitooooo** [langchain-ai/langgraph#1386]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

**{'messages': [{'content': 'hi', 'role': 'user'}]}**
```shell
[{'step': -2}:checkpoint] State at the end of step {'step': -2}:
{'messages': []}
[0:tasks] Starting step 0 with 1 task:
- __start__ -> {'messages': [{'content': 'hi', 'role': 'user'}]}
[0:writes] Finished step 0 with writes to 1 channel:
- messages -> [{'content': 'hi', 'role': 'user'}]
[{'step': -2}:checkpoint] State at the end of step {'step': -2}:
{'messages': [HumanMessage(content='hi', id='23d2de95-4eb3-4766-8cd3-2caad80dccbf')]}
[1:tasks] Starting step 1 with 1 task:
- agent -> {'is_last_step': False,
 'messages': [HumanMessage(content='hi', id='23d2de95-4eb3-4766-8cd3-2caad80dccbf')]}
[1:writes] Finished step 1 with writes to 1 channel:
- messages -> [AIMessage(content=' Hello! How can I assist you today?', response_metadata={'finish_reason': 'stop', 'model_name': 'Qwen2-72B-Instruct'}, id='run-0ddfab40-31e5-4fab-b8b4-b26f1659d854')]
```

### Error Message and Stack Trace (if applicable)

**[{'content': 'hi', 'role': 'user'}]**
```shell
[{'step': -2}:checkpoint] State at the end of step {'step': -2}:
{'messages': []}
[0:tasks] Starting step 0 with 1 task:
- __start__ -> [{'content': 'hi', 'role': 'user'}]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
    await response(scope, receive, send)
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/starlette/responses.py", line 258, in __call__
    async with anyio.create_task_group() as task_group:
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
    await func()
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response
    async for chunk in self.body_iterator:
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/langchain_openai_api_bridge/chat_completion/http_stream_response_adapter.py", line 10, in to_str_stream
    async for chunk in chunk_stream:
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/langchain_openai_api_bridge/core/utils/pydantic_async_iterator.py", line 7, in ato_dict
    async for obj in async_iter:
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/langchain_openai_api_bridge/chat_completion/langchain_stream_adapter.py", line 26, in ato_chat_completion_chunk_stream
    async for event in astream_event:
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 5290, in astream_events
    async for item in self.bound.astream_events(
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1247, in astream_events
    async for event in event_stream:
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/langchain_core/tracers/event_stream.py", line 1005, in _astream_events_implementation_v2
    await task
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/langchain_core/tracers/event_stream.py", line 965, in consume_astream
    async for _ in event_streamer.tap_output_aiter(run_id, stream):
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/langchain_core/tracers/event_stream.py", line 181, in tap_output_aiter
    first = await py_anext(output, default=sentinel)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/langchain_core/utils/aiter.py", line 78, in anext_impl
    return await __anext__(iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/valdanito/workspace/original/langgraph/libs/langgraph/langgraph/pregel/__init__.py", line 1277, in astream
    _panic_or_proceed(done, inflight, loop.step, asyncio.TimeoutError)
  File "/Users/valdanito/workspace/original/langgraph/libs/langgraph/langgraph/pregel/__init__.py", line 1456, in _panic_or_proceed
    raise exc
  File "/Users/valdanito/workspace/original/langgraph/libs/langgraph/langgraph/pregel/executor.py", line 123, in done
    task.result()
  File "/Users/valdanito/workspace/original/langgraph/libs/langgraph/langgraph/pregel/retry.py", line 72, in arun_with_retry
    async for _ in task.proc.astream(task.input, task.config):
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 875, in astream
    yield await self.ainvoke(input, config, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/valdanito/workspace/original/langgraph/libs/langgraph/langgraph/utils.py", line 114, in ainvoke
    ret = await self._acall_with_config(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/valdanito/install/conda/miniconda3/envs/gradio/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1835, in _acall_with_config
    output: Output = await asyncio.create_task(coro, context=context)  # type: ignore
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/valdanito/workspace/original/langgraph/libs/langgraph/langgraph/pregel/write.py", line 127, in _awrite
    values = await asyncio.gather(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/valdanito/workspace/original/langgraph/libs/langgraph/langgraph/utils.py", line 111, in ainvoke
    return self.invoke(input, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/valdanito/workspace/original/langgraph/libs/langgraph/langgraph/utils.py", line 102, in invoke
    ret = context.run(self.func, input, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/valdanito/workspace/original/langgraph/libs/langgraph/langgraph/graph/state.py", line 529, in _get_state_key
    raise InvalidUpdateError(f"Expected dict, got {input}")
langgraph.errors.InvalidUpdateError: Expected dict, got [{'role': 'user', 'content': 'hi'}]
```

### Description

When I got the error `langgraph.errors.InvalidUpdateError: Expected dict, got [{'role': 'user', 'content': 'hi'}]`, I checked the source code of langgraph.
I made simple modifications to the code -> https://github.com/Valdanitooooo/langgraph/commit/c2d05edcd04becf3619d025eb90f65d0966077a1, and my application runs well. I am not sure if my modifications will damage other features or if there are other better ways to fix this error. If my modifications are safe and constructive, please let me know and I will initiate a pull request.

### System Info

```
System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 22.6.0: Sun Dec 17 22:18:09 PST 2023; root:xnu-8796.141.3.703.2~2/RELEASE_X86_64
> Python Version:  3.11.9 (main, Apr 19 2024, 11:44:45) [Clang 14.0.6 ]

Package Information
-------------------
> langchain_core: 0.2.30
> langchain: 0.2.9
> langchain_community: 0.2.7
> langsmith: 0.1.85
> langchain_experimental: 0.0.62
> langchain_openai: 0.1.17
> langchain_openai_api_bridge: 0.11.1
> langchain_text_splitters: 0.2.1
> langchainhub: 0.1.20
> langgraph: 0.2.4
```

**Comment by vbarda** [comment]
could you please provide a minimal reproducible example for this issue? it looks like one of the nodes in your graph is making an update that is a list of messages instead of `{"messages": [list of messages]}`

**Comment by Valdanitooooo** [comment]
@vbarda I use https://github.com/samuelint/langchain-openai-api-bridge to build my agent API. Here is my code
### Server

```
import operator
from typing import Annotated, Sequence, TypedDict

import uvicorn
from fastapi import FastAPI, Security
from fastapi.security import APIKeyHeader
from langchain_community.tools import DuckDuckGoSearchResults
from langchain_core.messages import BaseMessage
from langchain_core.messages import ToolMessage, AIMessage
from langchain_core.runnables import Runnable, RunnableConfig
from langchain_openai_api_bridge.core import BaseAgentFactory
from langchain_openai_api_bridge.core.create_agent_dto import CreateAgentDto
from langchain_openai_api_bridge.fastapi import LangchainOpenaiApiBridgeFastAPI
from langgraph.graph import END, StateGraph, START
from langgraph.prebuilt import ToolExecutor
from langgraph.prebuilt import ToolInvocation
from pydantic import BaseModel
from starlette.middleware.cors import CORSMiddleware

from modules.common.utils import llm

tools = [DuckDuckGoSearchResults()]
tool_executor = ToolExecutor(tools)


class AgentState(TypedDict):
    messages: Annotated[Sequence[BaseMessage], operator.add]


def should_continue(state):
    messages = state["messages"]
    last_message = messages[-1]
    if not last_message.tool_calls:
        return "end"
    else:
        return "continue"


def call_model(state):
    messages = state["messages"]
    response = llm.invoke(messages)
    return {"messages": [response]}


def call_tool(state):
    messages = state["messages"]
    last_message = messages[-1]
    tool_invocations = []
    for tool_call in last_message.tool_calls:
        action = ToolInvocation(
            tool=tool_call["name"],
            tool_input=tool_call["args"],
        )
        tool_invocations.append(action)

    responses = tool_executor.batch(tool_invocations, return_exceptions=True)
    tool_messages = [
        ToolMessage(
            content=str(response),
            name=tc["name"],
            tool_call_id=tc["id"],
        )
        for tc, response in zip(last_message.tool_calls, responses)
    ]
    return {"messages": tool_messages}


def first_model(state):
    human_input = state["messages"][-1]["content"]
    return {
        "messages": [
            AIMessage(
                content="",
                tool_calls=[
                    {
                        "name": "reflection",
                        "args": {
                            "query": human_input,
                        },
                        "id": "tool_abcd123",
                    }
                ],
            )
        ]
    }


def create_graph():
    workflow = StateGraph(AgentState)

    workflow.add_node("first_agent", first_model)

    workflow.add_node("agent", call_model)
    workflow.add_node("action", call_tool)

    workflow.add_edge(START, "first_agent")

    workflow.add_conditional_edges(
        "agent",
        should_continue,
        {
            "continue": "action",
            "end": END,
        },
    )

    workflow.add_edge("action", "agent")

    workflow.add_edge("first_agent", "action")
    graph = workflow.compile(debug=True).with_config(
        RunnableConfig(
            configurable={"thread_id": "1"},
            recursion_limit=10, )
    )
    return graph


class TestAgent(BaseAgentFactory):
    def create_agent(self, dto: CreateAgentDto) -> Runnable:
        return create_graph()


app = FastAPI(
    title="Langchain Agent OpenAI API Bridge",
    version="1.0",
    description="OpenAI API exposing langchain agent",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["*"],
)

token_key = APIKeyHeader(name="Authorization")


class Token(BaseModel):
    token: str


def get_current_token(auth_key: str = Security(token_key)):
    return auth_key


rag_bridge = LangchainOpenaiApiBridgeFastAPI(
    app=app, agent_factory_provider=lambda: TestAgent()
)
rag_bridge.bind_openai_chat_completion(prefix="/test-agent")

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8888)

```

### Client

```
from openai import OpenAI

if __name__ == '__main__':
    openai_client = OpenAI(
        base_url="http://localhost:8888/test-agent/openai/v1",
        api_key="xxx"
    )

    chat_completion = openai_client.chat.completions.create(
        model="agent-model",
        messages=[
            {
                "role": "user",
                "content": 'hi',
            }
        ],
    )
    print(chat_completion.choices[0].message.content)

```

**Comment by vbarda** [comment]
@Valdanitooooo I am not familiar with `langchain_openai_api_bridge`, but looks like there is something wrong with how that library collects the inputs from `completions.create` --  it is not passing the input to the langgraph graph as a dict -- it's expecting `{"messages": [list of messages]}` and is getting just `[list of messages]`, so i don't think it's a langgraph issue. i don't see anything wrong with your langgraph code -- can you confirm that it is working without FastAPI / langchain openai bridge?

**Comment by Valdanitooooo** [comment]
> can you confirm that it is working without FastAPI / langchain openai bridge?

Yes, I can confirm that. I will further investigate this issue.
