### ISSUE TITLE
langgraph up broken again.. 

### ISSUE THREAD

**Issue by darthShana** [langchain-ai/langgraph#1456]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
langgraph up
```

### Error Message and Stack Trace (if applicable)

```shell
➜  langgraph-pyproject git:(master) ✗ langgraph up       
Starting LangGraph API server...
For local dev, requires env var LANGSMITH_API_KEY with access to LangGraph Cloud closed beta.
For production use, requires a license key in env var LANGGRAPH_CLOUD_LICENSE_KEY.
- Building...#0 building with "base" instance using docker-container driver

#1 [langgraph-api internal] load build definition from Dockerfile
#1 transferring dockerfile: 390B done
#1 DONE 0.0s

#2 [langgraph-api internal] load metadata for docker.io/langchain/langgraph-api:3.11
#2 DONE 1.0s

#3 [langgraph-api internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [langgraph-api 1/4] FROM docker.io/langchain/langgraph-api:3.11@sha256:b1b6f261959f2dce331ff39a94682ff0ebf241efd748a32701814bbca9686f14
#4 resolve docker.io/langchain/langgraph-api:3.11@sha256:b1b6f261959f2dce331ff39a94682ff0ebf241efd748a32701814bbca9686f14 done
#4 DONE 0.0s

#5 [langgraph-api internal] load build context
#5 transferring context: 13.16kB done
#5 DONE 0.0s

#6 [langgraph-api 3/4] RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*
#6 CACHED

#7 [langgraph-api 2/4] ADD . /deps/langgraph-pyproject
#7 CACHED

#8 [langgraph-api 4/4] WORKDIR /deps/langgraph-pyproject
#8 CACHED

#9 [langgraph-api] exporting to docker image format
#9 exporting layers done
#9 exporting manifest sha256:cb37ddeb855bb8bc557b687829160840dd889bbd03955af72ea9096924b8073f 0.0s done
#9 exporting config sha256:f448a5cbf11c3bb2aab986be8af4ddc7ef90780cb371bc8b50bdc3f3c117563a done
#9 sending tarball
#9 sending tarball 2.1s done
#9 ERROR: rpc error: code = Unknown desc = invalid diffID for layer 13: expected "sha256:f36a6bedaaa9c1b8aefacc1bf0f2338b52531ad4734368f5951d33f1f38e0268", got "sha256:0616d1187d8b092a7495f6e70312b77cb153f861008477b8ead31cd95c254f4e"

#10 [langgraph-api] importing to docker
#10 loading layer 2102b636cbbc 32.77kB / 241.94kB 1.8s done
#10 loading layer f36a6bedaaa9 557.06kB / 83.64MB 1.8s done
#10 ERROR: invalid diffID for layer 13: expected "sha256:f36a6bedaaa9c1b8aefacc1bf0f2338b52531ad4734368f5951d33f1f38e0268", got "sha256:0616d1187d8b092a7495f6e70312b77cb153f861008477b8ead31cd95c254f4e"
------
 > [langgraph-api] exporting to docker image format:
------
------
 > [langgraph-api] importing to docker:
------
failed to solve: rpc error: code = Unknown desc = invalid diffID for layer 13: expected "sha256:f36a6bedaaa9c1b8aefacc1bf0f2338b52531ad4734368f5951d33f1f38e0268", got "sha256:0616d1187d8b092a7495f6e70312b77cb153f861008477b8ead31cd95c254f4e"
```

### Description

Hi Team
The command
```bash
 langgraph up
```
stopped working, it was working a few hours ago, I dont think its due to any change i have made
A similar thing happened a few day ago, They suggested I do
```bash
docker system prune
```
However this time it did NOT resolve the issue. Also tried deleting all the docker images, but no luck

Any help would be  great;y appreciated
thanks

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP PREEMPT_DYNAMIC Sun Aug 11 15:32:50 UTC 2024
> Python Version:  3.12.4 (main, Jun  7 2024, 00:00:00) [GCC 14.1.1 20240607 (Red Hat 14.1.1-5)]

Package Information
-------------------
> langchain_core: 0.1.52
> langchain_community: 0.0.38
> langsmith: 0.1.77
> langchain_cli: 0.0.25
> langserve: 0.2.2

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph

**Comment by vbarda** [comment]
@darthShana is this still happening? as a last resort, perhaps consider reinstalling docker?

**Comment by darthShana** [comment]
hi @vbarda  yea its still happening
tried reinstalling, but same error
So its working for everyone else?

**Comment by vbarda** [comment]
i couldn't reproduce the issue, and I haven't seen it before -- could you perhaps paste your `langgraph.json`?

**Comment by darthShana** [comment]
hi @vbarda i delete all my docker images and then did a prune 
now im getting

```bash
langgraph-postgres-1  | 2024-08-28 04:50:40.201 UTC [1] LOG:  database system is ready to accept connections
langgraph-api-1       | Traceback (most recent call last):
langgraph-api-1       |   File "/usr/local/bin/uvicorn", line 8, in <module>
langgraph-api-1       |     sys.exit(main())
langgraph-api-1       |              ^^^^^^
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
langgraph-api-1       |     return self.main(*args, **kwargs)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
langgraph-api-1       |     rv = self.invoke(ctx)
langgraph-api-1       |          ^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
langgraph-api-1       |     return ctx.invoke(self.callback, **ctx.params)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
langgraph-api-1       |     return __callback(*args, **kwargs)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 410, in main
langgraph-api-1       |     run(
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 577, in run
langgraph-api-1       |     server.run()
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
langgraph-api-1       |     return asyncio.run(self.serve(sockets=sockets))
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
langgraph-api-1       |     return runner.run(main)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
langgraph-api-1       |     return self._loop.run_until_complete(task)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
langgraph-api-1       |     await self._serve(sockets)
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
langgraph-api-1       |     config.load()
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 434, in load
langgraph-api-1       |     self.loaded_app = import_from_string(self.app)
langgraph-api-1       |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
langgraph-api-1       |     module = importlib.import_module(module_str)
langgraph-api-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
langgraph-api-1       |     return _bootstrap._gcd_import(name[level:], package, level)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
langgraph-api-1       |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
langgraph-api-1       |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
langgraph-api-1       |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
langgraph-api-1       |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
langgraph-api-1       |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
langgraph-api-1       |   File "/api/langgraph_api/server.py", line 6, in <module>
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/langgraph_license/middleware.py", line 10, in <module>
langgraph-api-1       |     from langgraph_license.validation import get_license_status
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/langgraph_license/validation.py", line 10, in <module>
langgraph-api-1       |     from langgraph_api import config
langgraph-api-1       |   File "/api/langgraph_api/config.py", line 10, in <module>
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/starlette/config.py", line 98, in __call__
langgraph-api-1       |     return self.get(key, cast, default)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/starlette/config.py", line 115, in get
langgraph-api-1       |     raise KeyError(f"Config '{key}' is missing, and has no default.")
langgraph-api-1       | KeyError: "Config 'REDIS_URI' is missing, and has no default."
Aborting on container exit...
```
I think this might be a langgraph issue, as im not using redit anywhere at the moment

**Comment by vbarda** [comment]
can you upgrade langgraph-cli?

**Comment by darthShana** [comment]
nice working again now...
