### ISSUE TITLE
`langgraph up` error with `docker.io/langchain/langgraph-api:3.11` image 

### ISSUE THREAD

**Issue by seyeong-han** [langchain-ai/langgraph#1468]
### Example Code

```
langgraph up
```

### Error Message and Stack Trace (if applicable)

```shell
Starting LangGraph API server...
For local dev, requires env var LANGSMITH_API_KEY with access to LangGraph Cloud closed beta.
For production use, requires a license key in env var LANGGRAPH_CLOUD_LICENSE_KEY.
| Pulling...+ docker pull langchain/langgraph-api:3.11
\ Pulling...3.11: Pulling from langchain/langgraph-api
Digest: sha256:f38476de9d38e566a93346da0cc4f7b83329590721d94876ba361b27a1aa23ee
Status: Image is up to date for langchain/langgraph-api:3.11
docker.io/langchain/langgraph-api:3.11
...
langgraph-api-1       | 2024-08-26T01:34:36.616232Z [info     ] Waiting for application startup. [uvicorn.error] api_revision=20fd12a api_variant=licensed filename=on.py func_name=startup lineno=48
langgraph-api-1       | 2024-08-26T01:34:36.616422Z [warning  ] No license key found, running in test mode with LangSmith API key. For production use, set LANGGRAPH_CLOUD_LICENSE_KEY in environment. [langgraph_license.validation] api_revision=20fd12a api_variant=licensed filename=validation.py func_name=get_license_status lineno=80
langgraph-api-1       | 2024-08-26T01:34:36.916378Z [info     ] HTTP Request: GET https://api.smith.langchain.com/auth?langgraph-api=true "HTTP/1.1 200 OK" [httpx] api_revision=20fd12a api_variant=licensed filename=_client.py func_name=_send_single_request lineno=1773
langgraph-api-1       | 2024-08-26T01:34:36.963153Z [error    ] Traceback (most recent call last):
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 730, in lifespan
langgraph-api-1       |     async with self.lifespan_context(app) as maybe_state:
langgraph-api-1       |   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
langgraph-api-1       |     return await anext(self.gen)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/api/langgraph_api/lifespan.py", line 21, in lifespan
langgraph-api-1       |   File "/api/langgraph_api/shared/graph.py", line 147, in collect_graphs_from_env
langgraph-api-1       |   File "/api/langgraph_api/shared/graph.py", line 113, in is_js_spec
langgraph-api-1       |   File "<frozen posixpath>", line 118, in splitext
langgraph-api-1       | TypeError: expected str, bytes or os.PathLike object, not NoneType
langgraph-api-1       |  [uvicorn.error] api_revision=20fd12a api_variant=licensed filename=on.py func_name=send lineno=121
langgraph-api-1       | 2024-08-26T01:34:36.963336Z [error    ] Application startup failed. Exiting. [uvicorn.error] api_revision=20fd12a api_variant=licensed filename=on.py func_name=startup lineno=59
langgraph-api-1 exited with code 3
Command exited with non-zero status 3.
```

### Description

I was using `langgraph` on my custom application perfectly until yesterday, but I just got that error today.  
I didn't change any `langgraph.json` and requirements, but I am encountering an internal error with langgraph.
What I found is that the `docker.io/langchain/langgraph-api:3.11` image keeps updating today.
Today, I saw two new updates for that image, as shown in the screenshot below.

So my questions:
- Is the `docker.io/langchain/langgraph-api:3.11` unstable version yet?
- Can I specify the version of `langgraph-api docker image` by using `langgraph.json` or other configurations?

![image](https://github.com/user-attachments/assets/b6f1a293-c018-41c3-be3c-edd29c9d7b4d)

### System Info

```
langchain==0.2.14
langchain-core==0.2.34
langchain-openai==0.1.22
langchain-text-splitters==0.2.2
```
This was my working requirement until yesterday.
I also tested `langgraph up` by upgrading all `langchain` and `langgraph` packages but got the same error.

**Comment by gbaian10** [comment]
I also encountered a similar problem.

```shell
langgraph-api-1       | 2024-08-26T08:27:28.539258Z [error    ] Traceback (most recent call last):
langgraph-api-1       |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 730, in lifespan
langgraph-api-1       |     async with self.lifespan_context(app) as maybe_state:
langgraph-api-1       |   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
langgraph-api-1       |     return await anext(self.gen)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/api/langgraph_api/lifespan.py", line 21, in lifespan
langgraph-api-1       |   File "/api/langgraph_api/shared/graph.py", line 175, in collect_graphs_from_env
langgraph-api-1       |   File "/usr/local/lib/python3.12/site-packages/langchain_core/runnables/config.py", line 589, in run_in_executor
langgraph-api-1       |     return await asyncio.get_running_loop().run_in_executor(
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
langgraph-api-1       |     result = self.fn(*self.args, **self.kwargs)
langgraph-api-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/usr/local/lib/python3.12/site-packages/langchain_core/runnables/config.py", line 580, in wrapper
langgraph-api-1       |     return func(*args, **kwargs)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/api/langgraph_api/shared/graph.py", line 206, in _graph_from_spec
langgraph-api-1       |   File "/api/langgraph_api/shared/graph.py", line 203, in _graph_from_spec
langgraph-api-1       |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
langgraph-api-1       |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
langgraph-api-1       |   File "/deps/__outer_app/src/agent.py", line 6, in <module>
langgraph-api-1       |     from src.graph.check_time_graph import CheckTimeGraph
langgraph-api-1       | ModuleNotFoundError: No module named 'src'
langgraph-api-1       | Could not import python module for graph: GraphSpec(id='agent', path='/deps/__outer_app/src/agent.py', module=None, variable='graph')
langgraph-api-1       |  [uvicorn.error] api_revision=20fd12a api_variant=licensed filename=on.py func_name=send lineno=121
langgraph-api-1       | 2024-08-26T08:27:28.539430Z [error    ] Application startup failed. Exiting. [uvicorn.error] api_revision=20fd12a api_variant=licensed filename=on.py func_name=startup lineno=59
langgraph-api-1 exited with code 3
```

**Comment by vbarda** [comment]
This is definitely a bug, we'll push a fix shortly

@gbaian10 `src` is unrelated to this issue

**Comment by vbarda** [comment]
@seyeong-han this issue is fixed now, let me know if you're still running into it

**Comment by seyeong-han** [comment]
I just tested it, and it is working!!
Thanks!

**Comment by ab94amz** [comment]
Not yet to me, how did you solve?

**Comment by jaruesink** [comment]
@vbarda does this fix also need to come to LangGraph Studio? I'm getting this same error when trying to run that.

**Comment by vbarda** [comment]
@jaruesink the latest images should be automatically pulled when using studio. i would recommend running `docker system prune` or manually deleting old langgraph api docker images and restarting studio. let me know if that doesn't fix your issue

**Comment by phfifofum** [comment]
is this error I have related to this at all?


#13 [langgraph-api] resolving provenance for metadata file
#13 DONE 0.0s
time="2025-02-10T15:07:14Z" level=warning msg="The \"line\" variable is not set. Defaulting to a blank string."
 Service langgraph-api  Building
 Service langgraph-api  Built
 Container ecomm-manager-langgraph-redis-1  Running
 Container ecomm-manager-langgraph-postgres-1  Running
 Container ecomm-manager-langgraph-api-1  Recreate
 Container ecomm-manager-langgraph-api-1  Recreated
 Container ecomm-manager-langgraph-redis-1  Waiting
 Container ecomm-manager-langgraph-postgres-1  Waiting
 Container ecomm-manager-langgraph-redis-1  Healthy
 Container ecomm-manager-langgraph-postgres-1  Healthy
 Container ecomm-manager-langgraph-api-1  Starting
 Container ecomm-manager-langgraph-api-1  Started
 Container ecomm-manager-langgraph-postgres-1  Waiting
 Container ecomm-manager-langgraph-api-1  Waiting
 Container ecomm-manager-langgraph-redis-1  Waiting
 Container ecomm-manager-langgraph-redis-1  Healthy
 Container ecomm-manager-langgraph-postgres-1  Healthy
container ecomm-manager-langgraph-api-1 exited (3)
