### ISSUE TITLE
Send for subgraph has an error about checkpoint id

### ISSUE THREAD

**Issue by sangmandu** [langchain-ai/langgraph#1618]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
from langgraph.graph import START, StateGraph, END
from langgraph.constants import Send
from langgraph.checkpoint.memory import MemorySaver
from langchain_core.runnables import RunnableLambda

import operator
from collections.abc import Sequence
from typing import Annotated, TypedDict, Union

from langchain_core.messages import BaseMessage, AIMessage, HumanMessage
import time


class SupervisorState(TypedDict):
    messages: Annotated[Sequence[Union[BaseMessage, dict]], operator.add]


class AgentState(TypedDict):
    messages: Annotated[Sequence[Union[BaseMessage, dict]], operator.add]


def supervisor_graph(checkpointer):
    def router(state: SupervisorState):
        return [Send("return_bad", {"messages": [AIMessage(content="bad")]})]

    supervisor = StateGraph(SupervisorState)
    supervisor.add_edge(START, "return_good")

    supervisor.add_node("return_good", RunnableLambda(lambda x:{"messages": [AIMessage(content="good")]}))
    supervisor.add_conditional_edges("return_good", router, ["return_bad"])

    supervisor.add_node("return_bad", agent_graph(checkpointer))
    supervisor.add_edge("return_bad", END)

    return supervisor.compile(checkpointer)


def agent_graph(checkpointer):
    agent = StateGraph(AgentState)
    agent.add_edge(START, "return_bad")

    agent.add_node("return_bad", RunnableLambda(lambda x:{"messages": [AIMessage(content="bad")]}))
    agent.add_edge("return_bad", END)

    return agent.compile(checkpointer=checkpointer)


memory = MemorySaver()
g = supervisor_graph(checkpointer=memory)

thread_id = str(time.time())
config = {
	"configurable": {
		"thread_id": thread_id,
	}
}
g.invoke(
	{
		"inputs": {"language": "Korean"},
		"messages": [HumanMessage(content="how do you linke this dress?")]
	},
	config
)
```

### Error Message and Stack Trace (if applicable)

```shell
[chain/start] [chain:LangGraph] Entering Chain run with input:
[inputs]
[chain/start] [chain:LangGraph > chain:__start__] Entering Chain run with input:
[inputs]
[chain/end] [chain:LangGraph > chain:__start__] [0ms] Exiting Chain run with output:
[outputs]
[chain/start] [chain:LangGraph > chain:return_good] Entering Chain run with input:
[inputs]
[chain/start] [chain:LangGraph > chain:return_good > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/end] [chain:LangGraph > chain:return_good > chain:RunnableLambda] [0ms] Exiting Chain run with output:
[outputs]
[chain/start] [chain:LangGraph > chain:return_good > chain:ChannelWrite<return_good,messages>] Entering Chain run with input:
[inputs]
[chain/end] [chain:LangGraph > chain:return_good > chain:ChannelWrite<return_good,messages>] [0ms] Exiting Chain run with output:
[outputs]
[chain/start] [chain:LangGraph > chain:return_good > chain:router] Entering Chain run with input:
[inputs]
[chain/end] [chain:LangGraph > chain:return_good > chain:router] [0ms] Exiting Chain run with output:
[outputs]
[chain/start] [chain:LangGraph > chain:return_good > chain:ChannelWrite<return_bad>] Entering Chain run with input:
[inputs]
[chain/end] [chain:LangGraph > chain:return_good > chain:ChannelWrite<return_bad>] [0ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:LangGraph > chain:return_good] [3ms] Exiting Chain run with output:
[outputs]
[chain/start] [chain:LangGraph > chain:return_bad] Entering Chain run with input:
[inputs]
[chain/start] [chain:LangGraph > chain:return_bad > chain:LangGraph] Entering Chain run with input:
[inputs]
[chain/error] [chain:LangGraph > chain:return_bad > chain:LangGraph] [1ms] Chain run errored with error:
"KeyError('checkpoint_id')Traceback (most recent call last):\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/__init__.py\", line 908, in stream\n    while loop.tick(\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/loop.py\", line 206, in tick\n    self._first(input_keys=input_keys)\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/loop.py\", line 356, in _first\n    self._put_checkpoint({\"source\": \"input\", \"writes\": self.input})\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/loop.py\", line 377, in _put_checkpoint\n    id=self.config[\"configurable\"][\"checkpoint_id\"]\n\n\nKeyError: 'checkpoint_id'"
[chain/error] [chain:LangGraph > chain:return_bad] [3ms] Chain run errored with error:
"KeyError('checkpoint_id')Traceback (most recent call last):\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langchain_core/runnables/base.py\", line 2876, in invoke\n    input = context.run(step.invoke, input, config, **kwargs)\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/__init__.py\", line 1307, in invoke\n    for chunk in self.stream(\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/__init__.py\", line 908, in stream\n    while loop.tick(\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/loop.py\", line 206, in tick\n    self._first(input_keys=input_keys)\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/loop.py\", line 356, in _first\n    self._put_checkpoint({\"source\": \"input\", \"writes\": self.input})\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/loop.py\", line 377, in _put_checkpoint\n    id=self.config[\"configurable\"][\"checkpoint_id\"]\n\n\nKeyError: 'checkpoint_id'"
[chain/error] [chain:LangGraph] [17ms] Chain run errored with error:
"KeyError('checkpoint_id')Traceback (most recent call last):\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/__init__.py\", line 993, in stream\n    _panic_or_proceed(all_futures, loop.step)\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/__init__.py\", line 1423, in _panic_or_proceed\n    raise exc\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/executor.py\", line 60, in done\n    task.result()\n\n\n  File \"/usr/local/lib/python3.9/concurrent/futures/_base.py\", line 439, in result\n    return self.__get_result()\n\n\n  File \"/usr/local/lib/python3.9/concurrent/futures/_base.py\", line 391, in __get_result\n    raise self._exception\n\n\n  File \"/usr/local/lib/python3.9/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n\n\n  File \"/usr/local/lib/python3.9/site-packages/opentelemetry/instrumentation/threading/__init__.py\", line 143, in wrapped_func\n    return original_func(*func_args, **func_kwargs)\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/retry.py\", line 26, in run_with_retry\n    task.proc.invoke(task.input, task.config)\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langchain_core/runnables/base.py\", line 2876, in invoke\n    input = context.run(step.invoke, input, config, **kwargs)\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/__init__.py\", line 1307, in invoke\n    for chunk in self.stream(\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/__init__.py\", line 908, in stream\n    while loop.tick(\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/loop.py\", line 206, in tick\n    self._first(input_keys=input_keys)\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/loop.py\", line 356, in _first\n    self._put_checkpoint({\"source\": \"input\", \"writes\": self.input})\n\n\n  File \"/usr/local/lib/python3.9/site-packages/langgraph/pregel/loop.py\", line 377, in _put_checkpoint\n    id=self.config[\"configurable\"][\"checkpoint_id\"]\n\n\nKeyError: 'checkpoint_id'"
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[8], line 56
     50 thread_id = str(time.time())
     51 config = {
     52 	"configurable": {
     53 		"thread_id": thread_id,
     54 	}
     55 }
---> 56 g.invoke(
     57 	{
     58 		"inputs": {"language": "Korean"},
     59 		"messages": [HumanMessage(content="how do you linke this dress?")]
     60 	},
     61 	config
     62 )

File /usr/local/lib/python3.9/site-packages/langgraph/pregel/__init__.py:1307, in Pregel.invoke(self, input, config, stream_mode, output_keys, interrupt_before, interrupt_after, debug, **kwargs)
   1305 else:
   1306     chunks = []
-> 1307 for chunk in self.stream(
   1308     input,
   1309     config,
   1310     stream_mode=stream_mode,
   1311     output_keys=output_keys,
   1312     interrupt_before=interrupt_before,
   1313     interrupt_after=interrupt_after,
   1314     debug=debug,
   1315     **kwargs,
   1316 ):
   1317     if stream_mode == "values":
   1318         latest = chunk

File /usr/local/lib/python3.9/site-packages/langgraph/pregel/__init__.py:993, in Pregel.stream(self, input, config, stream_mode, output_keys, interrupt_before, interrupt_after, debug)
    990         break
    992 # panic on failure or timeout
--> 993 _panic_or_proceed(all_futures, loop.step)
    994 # don't keep futures around in memory longer than needed
    995 del done, inflight, futures

File /usr/local/lib/python3.9/site-packages/langgraph/pregel/__init__.py:1423, in _panic_or_proceed(futs, step, timeout_exc_cls)
   1421             inflight.pop().cancel()
   1422         # raise the exception
-> 1423         raise exc
   1425 if inflight:
   1426     # if we got here means we timed out
   1427     while inflight:
   1428         # cancel all pending tasks

File /usr/local/lib/python3.9/site-packages/langgraph/pregel/executor.py:60, in BackgroundExecutor.done(self, task)
     58 def done(self, task: concurrent.futures.Future) -> None:
     59     try:
---> 60         task.result()
     61     except GraphInterrupt:
     62         # This exception is an interruption signal, not an error
     63         # so we don't want to re-raise it on exit
     64         self.tasks.pop(task)

File /usr/local/lib/python3.9/concurrent/futures/_base.py:439, in Future.result(self, timeout)
    437     raise CancelledError()
    438 elif self._state == FINISHED:
--> 439     return self.__get_result()
    441 self._condition.wait(timeout)
    443 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File /usr/local/lib/python3.9/concurrent/futures/_base.py:391, in Future.__get_result(self)
    389 if self._exception:
    390     try:
--> 391         raise self._exception
    392     finally:
    393         # Break a reference cycle with the exception in self._exception
    394         self = None

File /usr/local/lib/python3.9/concurrent/futures/thread.py:58, in _WorkItem.run(self)
     55     return
     57 try:
---> 58     result = self.fn(*self.args, **self.kwargs)
     59 except BaseException as exc:
     60     self.future.set_exception(exc)

File /usr/local/lib/python3.9/site-packages/opentelemetry/instrumentation/threading/__init__.py:143, in ThreadingInstrumentor.__wrap_thread_pool_submit.<locals>.wrapped_func(*func_args, **func_kwargs)
    141 try:
    142     token = context.attach(otel_context)
--> 143     return original_func(*func_args, **func_kwargs)
    144 finally:
    145     context.detach(token)

File /usr/local/lib/python3.9/site-packages/langgraph/pregel/retry.py:26, in run_with_retry(task, retry_policy)
     24 task.writes.clear()
     25 # run the task
---> 26 task.proc.invoke(task.input, task.config)
     27 # if successful, end
     28 break

File /usr/local/lib/python3.9/site-packages/langchain_core/runnables/base.py:2876, in RunnableSequence.invoke(self, input, config, **kwargs)
   2874 context.run(_set_config_context, config)
   2875 if i == 0:
-> 2876     input = context.run(step.invoke, input, config, **kwargs)
   2877 else:
   2878     input = context.run(step.invoke, input, config)

File /usr/local/lib/python3.9/site-packages/langgraph/pregel/__init__.py:1307, in Pregel.invoke(self, input, config, stream_mode, output_keys, interrupt_before, interrupt_after, debug, **kwargs)
   1305 else:
   1306     chunks = []
-> 1307 for chunk in self.stream(
   1308     input,
   1309     config,
   1310     stream_mode=stream_mode,
   1311     output_keys=output_keys,
   1312     interrupt_before=interrupt_before,
   1313     interrupt_after=interrupt_after,
   1314     debug=debug,
   1315     **kwargs,
   1316 ):
   1317     if stream_mode == "values":
   1318         latest = chunk

File /usr/local/lib/python3.9/site-packages/langgraph/pregel/__init__.py:908, in Pregel.stream(self, input, config, stream_mode, output_keys, interrupt_before, interrupt_after, debug)
    877 (
    878     debug,
    879     stream_modes,
   (...)
    890     debug=debug,
    891 )
    893 with SyncPregelLoop(
    894     input,
    895     config=config,
   (...)
    906     # channels are guaranteed to be immutable for the duration of the step,
    907     # with channel updates applied only at the transition between steps
--> 908     while loop.tick(
    909         input_keys=self.input_channels,
    910         interrupt_before=interrupt_before,
    911         interrupt_after=interrupt_after,
    912         manager=run_manager,
    913     ):
    914         # debug flag
    915         if debug:
    916             print_step_checkpoint(
    917                 loop.checkpoint_metadata,
    918                 loop.channels,
    919                 self.stream_channels_list,
    920             )

File /usr/local/lib/python3.9/site-packages/langgraph/pregel/loop.py:206, in PregelLoop.tick(self, input_keys, interrupt_after, interrupt_before, manager)
    203     raise RuntimeError("Cannot tick when status is no longer 'pending'")
    205 if self.input not in (INPUT_DONE, INPUT_RESUMING):
--> 206     self._first(input_keys=input_keys)
    207 elif all(task.writes for task in self.tasks):
    208     writes = [w for t in self.tasks for w in t.writes]

File /usr/local/lib/python3.9/site-packages/langgraph/pregel/loop.py:356, in PregelLoop._first(self, input_keys)
    349     assert not apply_writes(
    350         self.checkpoint,
    351         self.channels,
    352         discard_tasks + [PregelTaskWrites(INPUT, input_writes, [])],
    353         self.checkpointer_get_next_version,
    354     ), "Can't write to SharedValues in graph input"
    355     # save input checkpoint
--> 356     self._put_checkpoint({"source": "input", "writes": self.input})
    357 else:
    358     raise EmptyInputError(f"Received no input for {input_keys}")

File /usr/local/lib/python3.9/site-packages/langgraph/pregel/loop.py:377, in PregelLoop._put_checkpoint(self, metadata)
    366 if self._checkpointer_put_after_previous is not None:
    367     # create new checkpoint
    368     self.checkpoint_metadata = metadata
    369     self.checkpoint = create_checkpoint(
    370         self.checkpoint,
    371         self.channels,
    372         self.step,
    373         # child graphs keep at most one checkpoint per parent checkpoint
    374         # this is achieved by writing child checkpoints as progress is made
    375         # (so that error recovery / resuming from interrupt don't lose work)
    376         # but doing so always with an id equal to that of the parent checkpoint
--> 377         id=self.config["configurable"]["checkpoint_id"]
    378         if self.is_nested
    379         else None,
    380     )
    382     self.checkpoint_config = {
    383         **self.checkpoint_config,
    384         "configurable": {
   (...)
    389         },
    390     }
    392     channel_versions = self.checkpoint["channel_versions"].copy()

KeyError: 'checkpoint_id'
```

### Description

I am using Supervision framework and I think supervisor can call the agent two time at once. (for example when the question is "what's the weather in NewYork and SF" then Call the Document Agent("what's the weather of NewYork") and DocumentAgent("what's the weather of SanFrancisco")) So I choose the function Send but it is not working now. The above code completely reproduce this error. Why does this error raised? Can you fix it??

And, I try to give random checkpoint id.
and It helps for first time but when next second question I entered into, the chat history got something wrong. chat history lost some messages.
There are no documents about this checkpoint or checkpoin id and no examples of calling agent from supervisor by Send.
I can not figure out anything else about this. Plz help me. I am looking forward to your rapid reaction and update and explanation. So appreciate.

And lastly this is not directly related to this issues much but I wonder there are some state trash(=remains).
It means If I call the agent by Send and then I call the agent one more after that time, the state of agent is not initialized. I want to use the agent by Send for One-Time using but I guess it is not. It is your intent? Can I use One-Time agent that initialize everytime they are called or after returning the result to supervisor

### System Info

langgraph==0.2.12
langgraph-checkpoint==1.0.3

**Comment by vbarda** [comment]
yes, please update to the latest version

**Comment by endymion** [comment]
I'm seeing a similar problem with version 0.2.53, currently the latest version:
```
  File "/home/ec2-user/projects/Plexus/plexus/scores/LangGraphScore.py", line 674, in predict
    result = await self.workflow.ainvoke(state, config=config)
  File "/home/ec2-user/miniconda3/envs/py39/lib/python3.9/site-packages/langgraph/pregel/__init__.py", line 1980, in ainvoke
    async for chunk in self.astream(
  File "/home/ec2-user/miniconda3/envs/py39/lib/python3.9/site-packages/langgraph/pregel/__init__.py", line 1823, in astream
    async with AsyncPregelLoop(
  File "/home/ec2-user/miniconda3/envs/py39/lib/python3.9/site-packages/langgraph/pregel/loop.py", line 1000, in __aenter__
    self.checkpoint_previous_versions = self.checkpoint["channel_versions"].copy()
KeyError: 'channel_versions'
```
Does anyone have any idea what the root of this problem might be?  I'm looking for workarounds.

I'm experimenting with persistence through checkpointers and breakpoints, and this is my first experience so far: None of it works because of that.

I might be seeing the async version of the same malfunction?
