### ISSUE TITLE
AttributeError: 'CompiledStateGraph' object has no attribute 'copy

### ISSUE THREAD

**Issue by darthShana** [langchain-ai/langgraph#1634]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
workflow.add_conditional_edges(
    "tools",
    route_tool_results,
    {
        "assistant": "assistant",
        "update_transactions": "update_transactions"
    }
)
workflow.add_edge("ask_human", "assistant")
workflow.add_edge("update_transactions", "assistant")

# The checkpointer lets the graph persist its state
# this is a complete memory for the entire graph.
memory = MemorySaver()
graph = workflow.compile(checkpointer=memory, interrupt_before=["ask_human"],)
```

### Error Message and Stack Trace (if applicable)

```shell
langgraph-api-1       | 2024-09-06T04:08:36.068536Z [error    ] Background run failed          [langgraph_api.queue] api_revision=a4cec24 api_variant=licensed run_created_at=2024-09-06T04:08:35.993513+00:00 run_ended_at=2024-09-06T04:08:36.068297 run_exec_ms=1 run_id=1ef6c05b-0427-6f80-894f-61d9743f0482 run_started_at=2024-09-06T04:08:36.066956+00:00
langgraph-api-1       | Traceback (most recent call last):
langgraph-api-1       |   File "/api/langgraph_api/queue.py", line 92, in worker
langgraph-api-1       |   File "/usr/local/lib/python3.11/asyncio/tasks.py", line 489, in wait_for
langgraph-api-1       |     return fut.result()
langgraph-api-1       |            ^^^^^^^^^^^^
langgraph-api-1       |   File "/api/langgraph_api/shared/stream.py", line 225, in consume
langgraph-api-1       |   File "/api/langgraph_api/shared/stream.py", line 213, in consume
langgraph-api-1       |   File "/api/langgraph_api/shared/stream.py", line 90, in astream_state
langgraph-api-1       |   File "/api/langgraph_api/shared/graph.py", line 87, in get_graph
langgraph-api-1       | AttributeError: 'CompiledStateGraph' object has no attribute 'copy'
```

### Description

HI Team 
I started getting the following error when doing 
```typescript
this.client.runs.stream(
      this.thread.thread_id,
      this.assistant.assistant_id,
      { input, streamMode: 'messages' }
    ))
```

im running langgraph up

```bash
➜  langgraph-pyproject git:(master) ✗ langgraph up            
Starting LangGraph API server...
For local dev, requires env var LANGSMITH_API_KEY with access to LangGraph Cloud closed beta.
For production use, requires a license key in env var LANGGRAPH_CLOUD_LICENSE_KEY.
Ready!       
- API: http://localhost:8123
- Docs: http://localhost:8123/docs
- Debugger: https://smith.langchain.com/studio/?baseUrl=http://127.0.0.1:8123
langgraph-api-1       | 2024-09-06T04:07:24.911340Z [info     ] Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit) [uvicorn.error] api_revision=a4cec24 api_variant=licensed color_message=Uvicorn running on %s://%s:%d (Press CTRL+C to quit)
langgraph-api-1       | 2024-09-06T04:07:25.657213Z [info     ] GET /ok 200 1ms                [langgraph_api.server] api_revision=a4cec24 api_variant=licensed latency_ms=1 method=GET path=/ok path_params={} route=None status=200
langgraph-api-1       | 2024-09-06T04:08:25.730401Z [info     ] GET /ok 200 0ms                [langgraph_api.server] api_revision=a4cec24 api_variant=licensed latency_ms=0 method=GET path=/ok path_params={} route=None status=200
langgraph-api-1       | 2024-09-06T04:08:28.330420Z [info     ] POST /assistants 200 2ms       [langgraph_api.server] api_revision=a4cec24 api_variant=licensed latency_ms=2 method=POST path=/assistants path_params={} route=/assistants status=200
langgraph-api-1       | 2024-09-06T04:08:28.336284Z [info     ] POST /threads 200 2ms          [langgraph_api.server] api_revision=a4cec24 api_variant=licensed latency_ms=2 method=POST path=/threads path_params={} route=/threads status=200
langgraph-api-1       | 2024-09-06T04:08:36.067077Z [info     ] Starting background run        [langgraph_api.queue] api_revision=a4cec24 api_variant=licensed run_created_at=2024-09-06T04:08:35.993513+00:00 run_id=1ef6c05b-0427-6f80-894f-61d9743f0482 run_queue_ms=73 run_started_at=2024-09-06T04:08:36.066956+00:00
langgraph-api-1       | 2024-09-06T04:08:36.068536Z [error    ] Background run failed          [langgraph_api.queue] api_revision=a4cec24 api_variant=licensed run_created_at=2024-09-06T04:08:35.993513+00:00 run_ended_at=2024-09-06T04:08:36.068297 run_exec_ms=1 run_id=1ef6c05b-0427-6f80-894f-61d9743f0482 run_started_at=2024-09-06T04:08:36.066956+00:00
langgraph-api-1       | Traceback (most recent call last):
langgraph-api-1       |   File "/api/langgraph_api/queue.py", line 92, in worker
langgraph-api-1       |   File "/usr/local/lib/python3.11/asyncio/tasks.py", line 489, in wait_for
langgraph-api-1       |     return fut.result()
langgraph-api-1       |            ^^^^^^^^^^^^
langgraph-api-1       |   File "/api/langgraph_api/shared/stream.py", line 225, in consume
langgraph-api-1       |   File "/api/langgraph_api/shared/stream.py", line 213, in consume
langgraph-api-1       |   File "/api/langgraph_api/shared/stream.py", line 90, in astream_state
langgraph-api-1       |   File "/api/langgraph_api/shared/graph.py", line 87, in get_graph
langgraph-api-1       | AttributeError: 'CompiledStateGraph' object has no attribute 'copy'

```
Have tried all the usual suspects 
deleting all my docker images
docker system prune
poetry upgrade

but no luck

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP PREEMPT_DYNAMIC Mon Aug 19 14:09:30 UTC 2024
> Python Version:  3.12.5 (main, Aug  7 2024, 00:00:00) [GCC 14.2.1 20240801 (Red Hat 14.2.1-1)]

Package Information
-------------------
> langchain_core: 0.1.52
> langchain_community: 0.0.38
> langsmith: 0.1.77
> langchain_cli: 0.0.25
> langserve: 0.2.2

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph

**Comment by nfcampos** [comment]
This issue is fixed in the latest version, sorry about the disruption

**Comment by gbaian10** [comment]
![image](https://github.com/user-attachments/assets/7a7f3607-0c4c-494b-a984-21524e34b86f)
