### ISSUE TITLE
`CheckpointNS` `ConfigurableFieldSpec` model is not in sync with the Base SQL schema definitions

### ISSUE THREAD

**Issue by riyavsinha** [langchain-ai/langgraph#2033]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
from typing import Annotated
from typing_extensions import TypedDict
from langchain_openai import ChatOpenAI
from psycopg_pool import ConnectionPool, AsyncConnectionPool
from langgraph.checkpoint.postgres.aio import AsyncPostgresSaver
from db.utils import get_db_url
from langgraph.graph.message import add_messages
from langgraph.graph import StateGraph, START, END

apool = AsyncConnectionPool(
    conninfo=get_db_url(),
    max_size=20,
    open=False,
    kwargs={'autocommit': True, 'prepare_threshold': 0}
)


async def setup_async_checkpointer():
    await apool.open()
    apostgres_checkpointer = AsyncPostgresSaver(apool)
    await apostgres_checkpointer.setup()
    return apostgres_checkpointer

_apostgres_checkpointer = None


async def apostgres_checkpointer():
    global _apostgres_checkpointer
    if not _apostgres_checkpointer:
        _apostgres_checkpointer = await setup_async_checkpointer()
    return _apostgres_checkpointer


class State(TypedDict):
    messages: Annotated[list, add_messages]


async def graph():
    graph_builder = StateGraph(State)
    llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0)

    def chatbot(state: State):
        return {"messages": [llm.invoke(state["messages"])]}

    graph_builder.add_node("chatbot", chatbot)
    graph_builder.add_edge(START, "chatbot")
    graph_builder.add_edge("chatbot", END)
    memory = await apostgres_checkpointer()
    graph = graph_builder.compile(checkpointer=memory)
    return graph


async def main():
    g = await graph()
    config = {"configurable": {"thread_id": "1"}}
    config_model = g.config_schema(include=("configurable",))
    new_config = config_model(**config).model_dump()
    print(new_config)
    async for event in g.astream_log({"messages": [("user", 'hi')]}, config=new_config):
        continue

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
```

### Error Message and Stack Trace (if applicable)

```shell
$ python -m ex
error ignored terminating <psycopg.AsyncPipeline [IDLE, pipeline=ON] (host=localhost database=rdagents) at 0x11168fcd0>: pipeline aborted
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/riyavsinha/projects/rd-agents/ex.py", line 66, in <module>
    asyncio.run(main())
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/riyavsinha/projects/rd-agents/ex.py", line 59, in main
    async for event in g.astream_log({"messages": [("user", 'hi')]}, config=new_config):
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1110, in astream_log
    async for item in _astream_log_implementation(  # type: ignore
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/site-packages/langchain_core/tracers/log_stream.py", line 673, in _astream_log_implementation
    await task
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/site-packages/langchain_core/tracers/log_stream.py", line 627, in consume_astream
    async for chunk in runnable.astream(input, config, **kwargs):
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 1464, in astream
    async with AsyncPregelLoop(
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/site-packages/langgraph/pregel/loop.py", line 898, in __aexit__
    return await asyncio.shield(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/contextlib.py", line 730, in __aexit__
    raise exc_details[1]
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/contextlib.py", line 713, in __aexit__
    cb_suppress = await cb(*exc_details)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/site-packages/langgraph/pregel/executor.py", line 179, in __aexit__
    raise exc
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/site-packages/langgraph/pregel/loop.py", line 821, in _checkpointer_put_after_previous
    await prev
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/site-packages/langgraph/pregel/loop.py", line 823, in _checkpointer_put_after_previous
    await cast(BaseCheckpointSaver, self.checkpointer).aput(
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/site-packages/langgraph/checkpoint/postgres/aio.py", line 268, in aput
    async with self._cursor(pipeline=True) as cur:
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/contextlib.py", line 211, in __aexit__
    await anext(self.gen)
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/site-packages/psycopg_pool/pool_async.py", line 195, in connection
    yield conn
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/site-packages/langgraph/checkpoint/postgres/aio.py", line 34, in _get_connection
    yield conn
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/site-packages/langgraph/checkpoint/postgres/aio.py", line 341, in _cursor
    async with self.lock, conn.pipeline(), conn.cursor(
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/contextlib.py", line 211, in __aexit__
    await anext(self.gen)
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/site-packages/psycopg/connection_async.py", line 333, in pipeline
    async with pipeline:
  File "/Users/riyavsinha/opt/miniconda3/envs/rdagents/lib/python3.11/site-packages/psycopg/_pipeline.py", line 293, in __aexit__
    raise exc2.with_traceback(None)
psycopg.errors.NotNullViolation: null value in column "checkpoint_ns" of relation "checkpoint_blobs" violates not-null constraint
DETAIL:  Failing row contains (1, null, __start__, 00000000000000000000000000000001.0.28923935122858313, msgpack, \x81a86d657373616765739192a475736572a26869).
```

### Description

When using the config schema from the Langgraph Runnable to validate configs, the ConfigurableFieldSpec for CheckpointNS has default None. Then, when the Postgres checkpointer tries to put the checkpoint into the DB, this fails because None is converted to NULL, and the field is NOT NULL. 

Instead, as you can see [here](https://github.com/langchain-ai/langgraph/blob/main/libs/checkpoint-postgres/langgraph/checkpoint/postgres/base.py#L40), the SQL definition for this column has a default of an empty string, which is what the default should be for the CheckpointNS ConfigurableFied Spec.

I have already provided the fix in #2019 .

### System Info

$ python -m langchain_core.sys_info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
> Python Version:  3.11.0 (main, Mar  1 2023, 12:33:14) [Clang 14.0.6 ]

Package Information
-------------------
> langchain_core: 0.3.7
> langchain: 0.3.1
> langchain_community: 0.3.1
> langsmith: 0.1.129
> langchain_cli: 0.0.31
> langchain_experimental: 0.3.2
> langchain_huggingface: 0.1.0
> langchain_openai: 0.2.1
> langchain_postgres: 0.0.12
> langchain_text_splitters: 0.3.0
> langgraph: 0.2.34
> langserve: 0.3.0

Other Dependencies
------------------
> aiohttp: 3.9.5
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.6
> fastapi: 0.110.3
> gitpython: 3.1.43
> gritql: 0.1.5
> httpx: 0.27.0
> huggingface-hub: 0.23.4
> jsonpatch: 1.33
> langgraph-checkpoint: 2.0.0
> langserve[all]: Installed. No version info available.
> numpy: 1.26.4
> openai: 1.51.0
> orjson: 3.10.3
> packaging: 23.2
> pgvector: 0.2.5
> psycopg: 3.1.19
> psycopg-pool: 3.2.2
> pydantic: 2.9.2
> pydantic-settings: 2.5.2
> PyYAML: 6.0.1
> requests: 2.32.3
> sentence-transformers: 3.0.1
> SQLAlchemy: 2.0.35
> sqlalchemy: 2.0.35
> sse-starlette: 1.8.2
> tenacity: 8.3.0
> tiktoken: 0.7.0
> tokenizers: 0.19.1
> tomlkit: 0.12.5
> transformers: 4.42.3
> typer[all]: Installed. No version info available.
> typing-extensions: 4.12.1
> uvicorn: 0.23.2

**Comment by vbarda** [comment]
@riyavsinha thanks for reporting and fixing! merging your change
