### ISSUE TITLE
Undefined table 'checkpoints' when using Postgres

### ISSUE THREAD

**Issue by vignesh-spericorn** [langchain-ai/langgraph#2062]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
from langgraph.checkpoint.postgres import PostgresSaver
from psycopg import Connection

DB_URI = "postgresql://postgres:postgres@localhost:5432/llama_db?sslmode=disable"
connection_kwargs = {
    "autocommit": True,
    "prepare_threshold": 0,
}

with Connection.connect(DB_URI, **connection_kwargs) as conn:
    checkpointer = PostgresSaver(conn)
    # NOTE: you need to call .setup() the first time you're using your checkpointer
    checkpointer.setup()
    # Finally, we compile it!
    app = workflow.compile(checkpointer=checkpointer)

    config = {"configurable": {"thread_id": "1"}}

    while True:
        user_input=input("User: ")
        if user_input.lower() in ["quit","q"]:
            print("Good Bye")
            break

        for event in app.stream({'messages': user_input}, config, stream_mode='updates'):
            for value in event.values():
                pass

            print_update(event)
            
        print("Assistant:",value["messages"][0].content)
```

### Error Message and Stack Trace (if applicable)

```shell
psycopg.errors.UndefinedTable: relation "checkpoints" does not exist
LINE 34: from checkpoints WHERE thread_id = $1 AND checkpoint_ns = $2...
```

### Description

I was trying this [example](https://langchain-ai.github.io/langgraph/how-tos/memory/add-summary-conversation-history/) to create a custom chatbot with memory that is managed according to my logic instead of 6 messages. When i try to use Postgres  instead of `MemorySaver()` I get the above error message that 'checkpoints' table doesn't exist.

### System Info

Ubuntu 20.04
Python 3.11.10
langgraph==0.2.34
langgraph-checkpoint==2.0.1
langgraph-checkpoint-postgres==2.0.1

**Comment by vignesh-spericorn** [comment]
@vbarda i didn't get any errors i checked the Postgres DB it had the following tables 
checkpoint_blobs
checkpoint_writes
checkpoint_migrations

but checkpoints table is not present

**Comment by vbarda** [comment]
@vignesh-spericorn hmm, could you try deleting all checkpoint-related tables you mentioned and then re-running `.setup()`?

**Comment by kishorekkota** [comment]
I am having the same issue. Any assist would be helpful.

**Comment by vbarda** [comment]
@kishorekkota i would recommend deleting the tables & rerunning `.setup()` again. let me know if that fixes the issue

**Comment by kishorekkota** [comment]
looks like my issue was related to having bad data in thread id section. I was using UUID, i did not format it correctly to be treated as str.  Error message was some what misleading.

**Comment by vbarda** [comment]
@kishorekkota what was the error you were seeing? were you invoking the graph with UUID for thread ID?

**Comment by vbarda** [comment]
@vignesh-spericorn closing the issue due to inactivity, but feel free to reopen if you're still having an issue

**Comment by kishorekkota** [comment]
> @kishorekkota what was the error you were seeing? were you invoking the graph with UUID for thread ID?

Error was:
```
psycopg.errors.UndefinedFunction: operator does not exist: text = uuid LINE 34: from checkpoints WHERE thread_id = $1 AND checkpoint_ns = $2...
```
I was pushing UUID directly into the thread_id, making it an object, not a str. I have to fix it by  changing to take hex section and assign to thread_id.

** causing issue **
self.thread_id = uuid.uuid4()

** had to take hex ***
self.thread_id = uuid.uuid4().hex

**Comment by vbarda** [comment]
@kishorekkota got it, thanks! you can also just wrap it in a str -- `str(uuid.uuid4())`

**Comment by matescharnitzky** [comment]
I ran into this issue. For the async-connection string scenario, make sure to run .setup() with await.

```python
async with AsyncPostgresSaver.from_conn_string(DB_URI) as checkpointer:
    await checkpointer.setup()    
    graph = create_react_agent(model, tools=tools, checkpointer=checkpointer)
    config = {"configurable": {"thread_id": "6"}}
    res = await graph.ainvoke(
        {"messages": [("human", "what's the weather in nyc")]}, config
    )
    checkpoint_tuples = [c async for c in checkpointer.alist(config)]
```

**Comment by RadiBytes** [comment]
> I also ran into this issue. For the async-connection string scenario, make sure to run .setup() with await.
> 
> ```python
> async with AsyncPostgresSaver.from_conn_string(DB_URI) as checkpointer:
>     await checkpointer.setup()    
>     graph = create_react_agent(model, tools=tools, checkpointer=checkpointer)
>     config = {"configurable": {"thread_id": "6"}}
>     res = await graph.ainvoke(
>         {"messages": [("human", "what's the weather in nyc")]}, config
>     )
>     checkpoint_tuples = [c async for c in checkpointer.alist(config)]
> ```

This worked for me.

**Comment by timvw** [comment]
Faced the same issue... when hosting on FastAPI we manage the connection pool with fastapi [lifespan](https://fastapi.tiangolo.com/advanced/events/#lifespan)...

```python
@asynccontextmanager
async def lifespan(app: FastAPI):
    postgresql_settings = PostgresqlSettings()
    connection_kwargs = {
        "autocommit": True,
        "prepare_threshold": 0,
    }

    async with AsyncConnectionPool(
        conninfo=postgresql_settings.pg_connectionstring,
        kwargs=connection_kwargs,
    ) as pool:
        checkpointer = AsyncPostgresSaver(conn=pool)

        try:
            await checkpointer.setup()
        except Exception as e:
            print(f"Error setting up checkpointer: {e}")
            raise e

        graph = simple.build_graph(checkpointer)

        app.async_pool = pool
        app.checkpointer = checkpointer
        app.graph = graph

        yield

    await app.async_pool.close()
```

And in the app we invoke the graph as following:

```python
@router.post(
    "/{session_id}/messages",
    status_code=status.HTTP_201_CREATED,
    response_model=list[Message],
    summary="Add user message to the session",
)
async def add_user_message(
    session_id: str,
    add_message_req: AddMessageRequest,
    req: Request,
) -> list[Message]:
        config = RunnableConfig({"configurable": {"thread_id": session_id}})
        response = await graph.ainvoke({"messages": [("user", content)]}, config=config)
        ai_message = response["messages"][-1].content
        answer_messages = [BotMessage(content=ai_message)]
        return answer_messages
```

**Comment by Jackoder** [comment]
@vbarda Hello, I'm facing the same issue. Could you tell me why the thread table is undefined? Thanks, it's really useful.

```
2024-12-26T10:43:31.668461Z [error    ] Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/api/langgraph_api/lifespan.py", line 29, in lifespan
  File "/usr/local/lib/python3.11/site-packages/langgraph_storage/database.py", line 148, in start_pool
    await migrate()
  File "/usr/local/lib/python3.11/site-packages/langgraph_storage/database.py", line 108, in migrate
    await cur.execute(stmt.strip(), prepare=False)
  File "/usr/local/lib/python3.11/site-packages/psycopg/cursor_async.py", line 97, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "thread" does not exist
```

**Comment by rand0wn** [comment]
@vbarda Facing a similar issue in langgraph self hosted docker deployment, it occurs randomly and does not resolve but when I restart it is gone then occurs after some time randomly,

`2025-01-22T03:51:20.500756Z [info     ] Worker stats                   [langgraph_api.queue] active=0 api_revision=6148670 api_variant=local available=10 max=10
2025-01-22T03:51:20.502601Z [info     ] Queue stats                    [langgraph_api.queue] api_revision=6148670 api_variant=local med_age_secs=None min_age_secs=None n_pending=0
2025-01-22T03:52:15.155606Z [info     ] Postgres pool stats            [langgraph_storage.database] api_revision=6148670 api_variant=local pool_available=1 pool_max=150 pool_min=1 pool_size=1 requests_num=121 requests_waiting=0 usage_ms=131
2025-01-22T03:52:15.155984Z [info     ] Redis pool stats               [langgraph_storage.redis] api_revision=6148670 api_variant=local idle_connections=1 in_use_connections=0 max_connections=500
2025-01-22T03:52:19.554044Z [info     ] POST /threads 200 4ms          [langgraph_api.server] api_revision=6148670 api_variant=local latency_ms=4 method=POST path=/threads path_params={} proto=1.0 query_string= req_header={'host': 'agenticapi.sprouts.ai', 'x-real-ip': '34.59.133.118', 'x-forwarded-for': '34.59.133.118', 'x-forwarded-proto': 'https', 'connection': 'close', 'content-length': '50', 'user-agent': 'curl/7.88.1', 'accept': '*/*', 'content-type': 'application/json'} res_header={'content-length': '220', 'content-type': 'application/json'} route=/threads status=200
2025-01-22T03:52:20.633959Z [info     ] Worker stats                   [langgraph_api.queue] active=0 api_revision=6148670 api_variant=local available=10 max=10
2025-01-22T03:52:20.635698Z [info     ] Queue stats                    [langgraph_api.queue] api_revision=6148670 api_variant=local med_age_secs=None min_age_secs=None n_pending=0
2025-01-22T03:53:15.158586Z [info     ] Postgres pool stats            [langgraph_storage.database] api_revision=6148670 api_variant=local pool_available=1 pool_max=150 pool_min=1 pool_size=1 requests_num=120 requests_waiting=0 usage_ms=135
2025-01-22T03:53:15.159158Z [info     ] Redis pool stats               [langgraph_storage.redis] api_revision=6148670 api_variant=local idle_connections=1 in_use_connections=0 max_connections=500
2025-01-22T03:53:19.732438Z [info     ] POST /threads 200 5ms          [langgraph_api.server] api_revision=6148670 api_variant=local latency_ms=5 method=POST path=/threads path_params={} proto=1.0 query_string= req_header={'host': 'agenticapi.sprouts.ai', 'x-real-ip': '34.59.133.118', 'x-forwarded-for': '34.59.133.118', 'x-forwarded-proto': 'https', 'connection': 'close', 'content-length': '50', 'user-agent': 'curl/7.88.1', 'accept': '*/*', 'content-type': 'application/json'} res_header={'content-length': '220', 'content-type': 'application/json'} route=/threads status=200
2025-01-22T03:53:20.770805Z [info     ] Worker stats                   [langgraph_api.queue] active=0 api_revision=6148670 api_variant=local available=10 max=10
2025-01-22T03:53:20.772269Z [info     ] Queue stats                    [langgraph_api.queue] api_revision=6148670 api_variant=local med_age_secs=None min_age_secs=None n_pending=0
2025-01-22T03:54:15.161527Z [info     ] Postgres pool stats            [langgraph_storage.database] api_revision=6148670 api_variant=local pool_available=1 pool_max=150 pool_min=1 pool_size=1 requests_num=121 requests_waiting=0 usage_ms=131
2025-01-22T03:54:15.162307Z [info     ] Redis pool stats               [langgraph_storage.redis] api_revision=6148670 api_variant=local idle_connections=1 in_use_connections=0 max_connections=500
2025-01-22T03:54:19.945370Z [info     ] POST /threads 200 2ms          [langgraph_api.server] api_revision=6148670 api_variant=local latency_ms=2 method=POST path=/threads path_params={} proto=1.0 query_string= req_header={'host': 'agenticapi.sprouts.ai', 'x-real-ip': '34.59.133.118', 'x-forwarded-for': '34.59.133.118', 'x-forwarded-proto': 'https', 'connection': 'close', 'content-length': '50', 'user-agent': 'curl/7.88.1', 'accept': '*/*', 'content-type': 'application/json'} res_header={'content-length': '220', 'content-type': 'application/json'} route=/threads status=200
2025-01-22T03:54:20.906608Z [info     ] Worker stats                   [langgraph_api.queue] active=0 api_revision=6148670 api_variant=local available=10 max=10
2025-01-22T03:54:20.907882Z [info     ] Queue stats                    [langgraph_api.queue] api_revision=6148670 api_variant=local med_age_secs=None min_age_secs=None n_pending=0
2025-01-22T03:55:02.228604Z [info     ] GET / 404 0ms                  [langgraph_api.server] api_revision=6148670 api_variant=local latency_ms=0 method=GET path=/ path_params={} proto=1.0 query_string= req_header={'host': 'agenticapi.sprouts.ai', 'x-real-ip': '107.191.47.164', 'x-forwarded-for': '107.191.47.164', 'x-forwarded-proto': 'https', 'connection': 'close', 'user-agent': 'pulsetic.com (+https://pulsetic.com)'} res_header={'content-length': '9', 'content-type': 'text/plain; charset=utf-8'} route=None status=404
2025-01-22T03:55:03.333802Z [info     ] GET / 404 0ms                  [langgraph_api.server] api_revision=6148670 api_variant=local latency_ms=0 method=GET path=/ path_params={} proto=1.0 query_string= req_header={'host': 'agenticapi.sprouts.ai', 'x-real-ip': '107.191.47.164', 'x-forwarded-for': '107.191.47.164', 'x-forwarded-proto': 'https', 'connection': 'close', 'user-agent': 'pulsetic.com (+https://pulsetic.com)'} res_header={'content-length': '9', 'content-type': 'text/plain; charset=utf-8'} route=None status=404
2025-01-22T03:55:15.162842Z [info     ] Postgres pool stats            [langgraph_storage.database] api_revision=6148670 api_variant=local pool_available=1 pool_max=150 pool_min=1 pool_size=1 requests_num=121 requests_waiting=0 usage_ms=137
2025-01-22T03:55:15.163744Z [info     ] Redis pool stats               [langgraph_storage.redis] api_revision=6148670 api_variant=local idle_connections=1 in_use_connections=0 max_connections=500
2025-01-22T03:55:15.703797Z [info     ] HTTP Request: POST https://api.smith.langchain.com/v1/metadata/submit "HTTP/1.1 204 No Content" [httpx] api_revision=6148670 api_variant=local
2025-01-22T03:55:20.157617Z [info     ] POST /threads 200 2ms          [langgraph_api.server] api_revision=6148670 api_variant=local latency_ms=2 method=POST path=/threads path_params={} proto=1.0 query_string= req_header={'host': 'agenticapi.sprouts.ai', 'x-real-ip': '34.59.133.118', 'x-forwarded-for': '34.59.133.118', 'x-forwarded-proto': 'https', 'connection': 'close', 'content-length': '50', 'user-agent': 'curl/7.88.1', 'accept': '*/*', 'content-type': 'application/json'} res_header={'content-length': '220', 'content-type': 'application/json'} route=/threads status=200
2025-01-22T03:55:21.051815Z [info     ] Worker stats                   [langgraph_api.queue] active=0 api_revision=6148670 api_variant=local available=10 max=10
2025-01-22T03:55:21.053296Z [info     ] Queue stats                    [langgraph_api.queue] api_revision=6148670 api_variant=local med_age_secs=None min_age_secs=None n_pending=0
2025-01-22T03:55:56.148067Z [error    ] Background worker scheduler failed [langgraph_api.queue] api_revision=6148670 api_variant=local
Traceback (most recent call last):
  File "/api/langgraph_api/queue.py", line 118, in queue
  File "/usr/local/lib/python3.11/contextlib.py", line 650, in enter_async_context
    result = await _enter(cm)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph_storage/ops.py", line 968, in next
    await conn.execute(
  File "/usr/local/lib/python3.11/site-packages/psycopg/connection_async.py", line 268, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "thread" does not exist at character 106
2025-01-22T03:55:56.672320Z [error    ] Background worker scheduler failed [langgraph_api.queue] api_revision=6148670 api_variant=local
Traceback (most recent call last):
  File "/api/langgraph_api/queue.py", line 118, in queue
  File "/usr/local/lib/python3.11/contextlib.py", line 650, in enter_async_context
    result = await _enter(cm)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph_storage/ops.py", line 968, in next
    await conn.execute(
  File "/usr/local/lib/python3.11/site-packages/psycopg/connection_async.py", line 268, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "run" does not exist
LINE 2:                 from run
                             ^
2025-01-22T03:55:57.173888Z [error    ] Background worker scheduler failed [langgraph_api.queue] api_revision=6148670 api_variant=local
Traceback (most recent call last):
  File "/api/langgraph_api/queue.py", line 118, in queue
  File "/usr/local/lib/python3.11/contextlib.py", line 650, in enter_async_context
    result = await _enter(cm)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph_storage/ops.py", line 968, in next
    await conn.execute(
  File "/usr/local/lib/python3.11/site-packages/psycopg/connection_async.py", line 268, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "run" does not exist
LINE 2:                 from run
                             ^
2025-01-22T03:55:57.675809Z [error    ] Background worker scheduler failed [langgraph_api.queue] api_revision=6148670 api_variant=local
Traceback (most recent call last):
  File "/api/langgraph_api/queue.py", line 118, in queue
  File "/usr/local/lib/python3.11/contextlib.py", line 650, in enter_async_context
    result = await _enter(cm)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph_storage/ops.py", line 968, in next
    await conn.execute(
  File "/usr/local/lib/python3.11/site-packages/psycopg/connection_async.py", line 268, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "run" does not exist
LINE 2:                 from run
                             ^
2025-01-22T03:55:58.177797Z [error    ] Background worker scheduler failed [langgraph_api.queue] api_revision=6148670 api_variant=local
Traceback (most recent call last):
  File "/api/langgraph_api/queue.py", line 118, in queue
  File "/usr/local/lib/python3.11/contextlib.py", line 650, in enter_async_context
    result = await _enter(cm)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph_storage/ops.py", line 968, in next
    await conn.execute(
  File "/usr/local/lib/python3.11/site-packages/psycopg/connection_async.py", line 268, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "run" does not exist
LINE 2:                 from run
                             ^
2025-01-22T03:55:58.682478Z [error    ] Background worker scheduler failed [langgraph_api.queue] api_revision=6148670 api_variant=local
Traceback (most recent call last):
  File "/api/langgraph_api/queue.py", line 118, in queue
  File "/usr/local/lib/python3.11/contextlib.py", line 650, in enter_async_context
    result = await _enter(cm)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph_storage/ops.py", line 968, in next
    await conn.execute(
  File "/usr/local/lib/python3.11/site-packages/psycopg/connection_async.py", line 268, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "run" does not exist
LINE 2:                 from run
                             ^
2025-01-22T03:55:59.185886Z [error    ] Background worker scheduler failed [langgraph_api.queue] api_revision=6148670 api_variant=local
Traceback (most recent call last):
  File "/api/langgraph_api/queue.py", line 118, in queue
  File "/usr/local/lib/python3.11/contextlib.py", line 650, in enter_async_context
    result = await _enter(cm)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph_storage/ops.py", line 968, in next
    await conn.execute(
  File "/usr/local/lib/python3.11/site-packages/psycopg/connection_async.py", line 268, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "run" does not exist
LINE 2:                 from run
                             ^`

**Comment by sddavid** [comment]
I was using the example showed in this link:
https://pypi.org/project/langgraph-checkpoint-postgres/2.0.19/

This is the example code:
```
from langgraph.checkpoint.postgres import PostgresSaver

write_config = {"configurable": {"thread_id": "1", "checkpoint_ns": ""}}
read_config = {"configurable": {"thread_id": "1"}}

DB_URI = "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
with PostgresSaver.from_conn_string(DB_URI) as checkpointer:
    # call .setup() the first time you're using the checkpointer
    checkpointer.setup()
    checkpoint = {
        "v": 1,
        "ts": "2024-07-31T20:14:19.804150+00:00",
        "id": "1ef4f797-8335-6428-8001-8a1503f9b875",
        "channel_values": {
            "my_key": "meow",
            "node": "node"
        },
        "channel_versions": {
            "__start__": 2,
            "my_key": 3,
            "start:node": 3,
            "node": 3
        },
        "versions_seen": {
            "__input__": {},
            "__start__": {
            "__start__": 1
            },
            "node": {
            "start:node": 2
            }
        },
        "pending_sends": [],
    }

    # store checkpoint
    checkpointer.put(write_config, checkpoint, {}, {})

    # load checkpoint
    checkpointer.get(read_config)

    # list checkpoints
    list(checkpointer.list(read_config))
```
When I ran it, I encountered the same error: psycopg.errors.UndefinedTable: The relation "checkpoints" does not exist.

My solution was to apply a 5-second sleep period after running checkpointer.setup(), and the error was resolved.

**Comment by alberto-agudo** [comment]
> I was using the example showed in this link: https://pypi.org/project/langgraph-checkpoint-postgres/2.0.19/
> 
> This is the example code:
> 
> ```
> from langgraph.checkpoint.postgres import PostgresSaver
> 
> write_config = {"configurable": {"thread_id": "1", "checkpoint_ns": ""}}
> read_config = {"configurable": {"thread_id": "1"}}
> 
> DB_URI = "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
> with PostgresSaver.from_conn_string(DB_URI) as checkpointer:
>     # call .setup() the first time you're using the checkpointer
>     checkpointer.setup()
>     checkpoint = {
>         "v": 1,
>         "ts": "2024-07-31T20:14:19.804150+00:00",
>         "id": "1ef4f797-8335-6428-8001-8a1503f9b875",
>         "channel_values": {
>             "my_key": "meow",
>             "node": "node"
>         },
>         "channel_versions": {
>             "__start__": 2,
>             "my_key": 3,
>             "start:node": 3,
>             "node": 3
>         },
>         "versions_seen": {
>             "__input__": {},
>             "__start__": {
>             "__start__": 1
>             },
>             "node": {
>             "start:node": 2
>             }
>         },
>         "pending_sends": [],
>     }
> 
>     # store checkpoint
>     checkpointer.put(write_config, checkpoint, {}, {})
> 
>     # load checkpoint
>     checkpointer.get(read_config)
> 
>     # list checkpoints
>     list(checkpointer.list(read_config))
> ```
> 
> When I ran it, I encountered the same error: psycopg.errors.UndefinedTable: The relation "checkpoints" does not exist.
> 
> My solution was to apply a 5-second sleep period after running checkpointer.setup(), and the error was resolved.

This also worked for me. Wasn't sure about it as I was using a specific search path when setting up the connection, so at first I thought maybe the queries were not finding the first schema in the search path and looking in the others. But it seems it's working for now after applying the 5-second sleep
