### ISSUE TITLE
DOC: Bug in Memory example

### ISSUE THREAD

**Issue by ltoniazzi** [langchain-ai/langgraph#2137]
### Bug
If I run the example in this [Memory migration page](https://python.langchain.com/docs/versions/migrating_memory/conversation_buffer_memory/#langgraph), then I get then this error:
```bash
Traceback (most recent call last):
  File "/Users/usr/file.py", line 33, in <module>
    app = workflow.compile(
          ^^^^^^^^^^^^^^^^^
  File "/Users/usr/.venv/lib/python3.11/site-packages/langgraph/graph/state.py", line 211, in compile
    self.validate(
  File "/Users/usr/.venv/lib/python3.11/site-packages/langgraph/graph/graph.py", line 273, in validate
    raise ValueError(f"Node '{node}' is a dead-end")
ValueError: Node 'model' is a dead-end
```

### Fix

A way to fix it can be:

```python
workflow.add_edge(START, "model")
workflow.add_node("model", call_model)
workflow.add_edge("model", END)  # <-- Add  this
```

**Comment by vbarda** [comment]
@ltoniazzi the code should work with or without an edge to `END` -- adding an edge to `END` doesn't actually do anything in this case. i just ran the code from the example and it works for me without an error

what version of langgraph are you using? could you check if it's still an issue in the latest version?

**Comment by ltoniazzi** [comment]
@vbarda Sure (I can do it Monday)

**Comment by ltoniazzi** [comment]
My bad, I was using a very old version of langgraph by mistake. Works fine on the newer versions.

**Comment by vbarda** [comment]
@ltoniazzi great -- glad it works!
