### ISSUE TITLE
Serialization error when executing traceback at the end of workflow execution

### ISSUE THREAD

**Issue by henryf3** [langchain-ai/langgraph#2155]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
from pydantic import BaseModel
from snowflake.snowpark import Session


class BaseModelWithExclusions(BaseModel):
    class Config:
        arbitrary_types_allowed = True  # Allow arbitrary types like Session


class GetCategoriesInput(BaseModelWithExclusions):
    sp_session: Session
    data: str


class SQLSnowparkQueryInput(BaseModelWithExclusions):
    sp_session: Session
    query: str



# in another file:
for s in self._workflow.stream(message=user_prompt):
        if "end" not in s:
            print("####")
            print(s)
            # print(s["messages"])
            print("----")

```

### Error Message and Stack Trace (if applicable)

```shell
Traceback (most recent call last):
  File "/Users/henrymac/Documents/data_athena_snowflake/src/multi_agents/workflows/chatbot_v0/graph.py", line 263, in <module>
    exec_thread_id = chatbot_manager.run()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/henrymac/Documents/data_athena_snowflake/src/multi_agents/workflows/chatbot_v0/graph.py", line 240, in run
    for s in self._workflow.stream(message=user_prompt):
  File "/Users/henrymac/Documents/data_athena_snowflake/.venv3.11/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 1240, in stream
    with SyncPregelLoop(
  File "/Users/henrymac/Documents/data_athena_snowflake/.venv3.11/lib/python3.11/site-packages/langgraph/pregel/loop.py", line 754, in __exit__
    return self.stack.__exit__(exc_type, exc_value, traceback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/henrymac/.pyenv/versions/3.11.2/lib/python3.11/contextlib.py", line 589, in __exit__
    raise exc_details[1]
  File "/Users/henrymac/.pyenv/versions/3.11.2/lib/python3.11/contextlib.py", line 574, in __exit__
    if cb(*exc_details):
       ^^^^^^^^^^^^^^^^
  File "/Users/henrymac/Documents/data_athena_snowflake/.venv3.11/lib/python3.11/site-packages/langgraph/pregel/executor.py", line 105, in __exit__
    task.result()
  File "/Users/henrymac/.pyenv/versions/3.11.2/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/henrymac/.pyenv/versions/3.11.2/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/henrymac/Documents/data_athena_snowflake/.venv3.11/lib/python3.11/site-packages/langgraph/pregel/loop.py", line 680, in _checkpointer_put_after_previous
    prev.result()
  File "/Users/henrymac/.pyenv/versions/3.11.2/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/henrymac/.pyenv/versions/3.11.2/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/henrymac/Documents/data_athena_snowflake/.venv3.11/lib/python3.11/site-packages/langgraph/pregel/executor.py", line 70, in done
    task.result()
  File "/Users/henrymac/.pyenv/versions/3.11.2/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/henrymac/.pyenv/versions/3.11.2/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/henrymac/.pyenv/versions/3.11.2/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/henrymac/Documents/data_athena_snowflake/.venv3.11/lib/python3.11/site-packages/langgraph/pregel/loop.py", line 682, in _checkpointer_put_after_previous
    cast(BaseCheckpointSaver, self.checkpointer).put(
  File "/Users/henrymac/Documents/data_athena_snowflake/.venv3.11/lib/python3.11/site-packages/langgraph/checkpoint/memory/__init__.py", line 330, in put
    self.serde.dumps_typed(c),
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/henrymac/Documents/data_athena_snowflake/.venv3.11/lib/python3.11/site-packages/langgraph/checkpoint/serde/jsonplus.py", line 192, in dumps_typed
    return "msgpack", _msgpack_enc(obj)
                      ^^^^^^^^^^^^^^^^^
  File "/Users/henrymac/Documents/data_athena_snowflake/.venv3.11/lib/python3.11/site-packages/langgraph/checkpoint/serde/jsonplus.py", line 476, in _msgpack_enc
    return enc.pack(data)
           ^^^^^^^^^^^^^^
  File "msgpack/_packer.pyx", line 279, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 276, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 265, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 213, in msgpack._cmsgpack.Packer._pack_inner
  File "msgpack/_packer.pyx", line 265, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 213, in msgpack._cmsgpack.Packer._pack_inner
  File "msgpack/_packer.pyx", line 265, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 232, in msgpack._cmsgpack.Packer._pack_inner
  File "msgpack/_packer.pyx", line 267, in msgpack._cmsgpack.Packer._pack
  File "/Users/henrymac/Documents/data_athena_snowflake/.venv3.11/lib/python3.11/site-packages/langgraph/checkpoint/serde/jsonplus.py", line 227, in _msgpack_default
    _msgpack_enc(
  File "/Users/henrymac/Documents/data_athena_snowflake/.venv3.11/lib/python3.11/site-packages/langgraph/checkpoint/serde/jsonplus.py", line 476, in _msgpack_enc
    return enc.pack(data)
           ^^^^^^^^^^^^^^
  File "msgpack/_packer.pyx", line 279, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 276, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 265, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 232, in msgpack._cmsgpack.Packer._pack_inner
  File "msgpack/_packer.pyx", line 265, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 213, in msgpack._cmsgpack.Packer._pack_inner
  File "msgpack/_packer.pyx", line 265, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 232, in msgpack._cmsgpack.Packer._pack_inner
  File "msgpack/_packer.pyx", line 265, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 213, in msgpack._cmsgpack.Packer._pack_inner
  File "msgpack/_packer.pyx", line 265, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 213, in msgpack._cmsgpack.Packer._pack_inner
  File "msgpack/_packer.pyx", line 265, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 213, in msgpack._cmsgpack.Packer._pack_inner
  File "msgpack/_packer.pyx", line 267, in msgpack._cmsgpack.Packer._pack
  File "/Users/henrymac/Documents/data_athena_snowflake/.venv3.11/lib/python3.11/site-packages/langgraph/checkpoint/serde/jsonplus.py", line 409, in _msgpack_default
    raise TypeError(f"Object of type {obj.__class__.__name__} is not serializable")
TypeError: Object of type Session is not serializable
```

### Description

I have defined two custom base models for my tool calls since I need to pass an active snowflake session to my tools. 
It works as expected, the workflow runs from start to end perfectly, but at the end of the workflow.stream execution, the traceback tries to do a serialization.

So, how can I modify this behaviour and use a different serialization to avoid this error?
```
for s in self._workflow.stream(message=user_prompt):
                if "end" not in s:
                    print("####")
                    print(s)
                    # print(s["messages"])
                    print("----")
```

### System Info

langchain==0.3.1
langchain-anthropic==0.2.1
langchain-core==0.3.6
langchain-openai==0.2.1
langchain-text-splitters==0.3.0

platform mac
python version 3.11

**Comment by vbarda** [comment]
@henryf3 there are two ways to solve this: 

(1) you can pass `Session` in the config instead of the state (e.g. `workflow.stream(inputs, config={"configurable": {"session": session}})`)

(2) you can implement a custom serializer on top of [JsonPlusSerializer](https://langchain-ai.github.io/langgraph/reference/checkpoints/#langgraph.checkpoint.serde.jsonplus.JsonPlusSerializer) that handles the `Session` objects

let me know if you have more questions!

**Comment by henryf3** [comment]
@vbarda thanks, it worked perfectly
