### ISSUE TITLE
DOC: Bug in Memory Store Example

### ISSUE THREAD

**Issue by ltoniazzi** [langchain-ai/langgraph#2320]
### Issue with current documentation:

I tried to reproduce the [Memory Store Example](https://langchain-ai.github.io/langgraph/concepts/persistence/#memory-store) but the `store` parameter seem to not being passed to the node, giving the error: 
```
TypeError: call_model() missing 1 required positional argument: 'store'
```
(Note that I might be making a mistake in the code below)

### Reproduce:

```python
from langgraph.store.memory import InMemoryStore
from langgraph.graph import StateGraph, START, END, MessagesState
from langgraph.checkpoint.memory import MemorySaver
from langchain_core.runnables.config import RunnableConfig
from langchain_core.stores import BaseStore
import uuid

# Store
in_memory_store = InMemoryStore()
user_id = "1"
namespace_for_memory = (user_id, "memories")
memory_id = str(uuid.uuid4())
memory = {"food_preference" : "I like pizza"}
in_memory_store.put(namespace_for_memory, memory_id, memory)

# Node
def call_model(state: MessagesState, config: RunnableConfig, store: BaseStore):
    return {"messages": [f"LLM received {state['messages']=}"]}

# Graph
workflow = StateGraph(MessagesState)
workflow.add_node("call_model", call_model)
workflow.add_edge(START, "call_model")
workflow.add_edge("call_model", END)
graph = workflow.compile(checkpointer=MemorySaver(), store=in_memory_store)

# Invoke the graph
config = {"configurable": {"thread_id": "1", "user_id": user_id}}

# Invoke
for update in graph.stream(
    {"messages": [{"role": "user", "content": "hi"}]}, config, stream_mode="updates"
):
    print(update)
```

### Trace:

```
Traceback (most recent call last):
  File "/Users/usr/Workspace/demo-langraph/examples/_bug_store.py", line 31, in <module>
    for update in graph.stream(
  File "/Users/usr/Workspace/demo-langraph/.venv/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 1315, in stream
    for _ in runner.tick(
  File "/Users/usr/Workspace/demo-langraph/.venv/lib/python3.11/site-packages/langgraph/pregel/runner.py", line 56, in tick
    run_with_retry(t, retry_policy)
  File "/Users/usr/Workspace/demo-langraph/.venv/lib/python3.11/site-packages/langgraph/pregel/retry.py", line 29, in run_with_retry
    task.proc.invoke(task.input, config)
  File "/Users/usr/Workspace/demo-langraph/.venv/lib/python3.11/site-packages/langgraph/utils/runnable.py", line 410, in invoke
    input = context.run(step.invoke, input, config, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usr/Workspace/demo-langraph/.venv/lib/python3.11/site-packages/langgraph/utils/runnable.py", line 184, in invoke
    ret = context.run(self.func, input, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: call_model() missing 1 required positional argument: 'store'
```

### Environment:

- `langgraph=0.2.39`

**Comment by vbarda** [comment]
@ltoniazzi you're using a wrong type annotation for `store` in `call_model`, it should be `from langgraph.store.base import BaseStore`

**Comment by TechKemon** [comment]
> @ltoniazzi you're using a wrong type annotation for `store` in `call_model`, it should be `from langgraph.store.base import BaseStore`

Hey, wanted to know how to clear the memory? Suppose we're making a chatbot and we want to empty InMemoryStore() object between sessions?
