### ISSUE TITLE
LangGraph with LangServe

### ISSUE THREAD

**Issue by mail2mhossain** [langchain-ai/langgraph#241]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code
```
import uvicorn
from fastapi import FastAPI  # Request, Response

# from fastapi.responses import RedirectResponse
from langserve import add_routes

# from langserve import APIHandler

from graph_generator import generate_graph

chain = generate_graph()


app = FastAPI(
    title="Research Assistant",
    version="1.0",
    description="Research Assistant",
)


add_routes(app, chain, path="/research_assistant")

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)


### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\validators.py", line 751, in find_validators
    if issubclass(type_, val_type):
TypeError: issubclass() arg 1 must be a class

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\uvicorn\config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "Z:\MHossain_OneDrive\OneDrive\ChatGPT\AI_Bot\Research_Assistant\app\server.py", line 21, in <module>
    add_routes(app, chain, path="/research_assistant")
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\langserve\server.py", line 362, in add_routes
    api_handler = APIHandler(
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\langserve\api_handler.py", line 553, in __init__
    runnable.get_input_schema(), "Input", model_namespace
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\langgraph\pregel\__init__.py", line 221, in get_input_schema
    return super().get_input_schema(config)
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\langchain_core\runnables\base.py", line 303, in get_input_schema
    return create_model(
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\langchain_core\runnables\utils.py", line 508, in create_model
    return _create_model_cached(__model_name, **field_definitions)
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\langchain_core\runnables\utils.py", line 521, in _create_model_cached
    return _create_model_base(
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\main.py", line 1024, in create_model
    return meta(__model_name, resolved_bases, namespace, **kwds)
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\main.py", line 197, in __new__
    fields[ann_name] = ModelField.infer(
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\fields.py", line 504, in infer
    return cls(
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\fields.py", line 434, in __init__
    self.prepare()
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\fields.py", line 555, in prepare
    self.populate_validators()
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\fields.py", line 829, in populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\validators.py", line 738, in find_validators
    yield make_typeddict_validator(type_, config)
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\validators.py", line 624, in make_typeddict_validator
    TypedDictModel = create_model_from_typeddict(
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\annotated_types.py", line 55, in create_model_from_typeddict
    return create_model(typeddict_cls.__name__, **kwargs, **field_definitions)
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\main.py", line 1024, in create_model
    return meta(__model_name, resolved_bases, namespace, **kwds)
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\main.py", line 197, in __new__
    fields[ann_name] = ModelField.infer(
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\fields.py", line 504, in infer
    return cls(
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\fields.py", line 434, in __init__
    self.prepare()
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\fields.py", line 550, in prepare
    self._type_analysis()
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\fields.py", line 756, in _type_analysis
    self.sub_fields = [self._create_sub_type(self.type_, '_' + self.name)]
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\fields.py", line 806, in _create_sub_type
    return self.__class__(
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\fields.py", line 434, in __init__
    self.prepare()
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\fields.py", line 555, in prepare
    self.populate_validators()
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\fields.py", line 829, in populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
  File "Z:\Users\User\anaconda3\envs\shariah_app_env\lib\site-packages\pydantic\v1\validators.py", line 760, in find_validators
    raise RuntimeError(f'error checking inheritance of {type_!r} (type: {display_as_type(type_)})')
RuntimeError: error checking inheritance of <built-in function any> (type: builtin_function_or_method)
```
### Description

I am trying to use langgraph with langserve, that is trying expose an API with langgraph workflow (workflow = StateGraph(NewsState))

### System Info

langchain==0.1.13
langchain-cli==0.0.21
langgraph==0.0.26
langserve==0.0.39

platform - Windows 11
python version - 3.9

**Comment by hinthornw** [comment]
Looks like there's a `validator` somewhere that's cauing issues. Do you have a code s nippet for that?

**Comment by hinthornw** [comment]
Gonna mark this as stale
