### ISSUE TITLE
langgraph-sdk(JS) broken on 0.0.26 in angular

### ISSUE THREAD

**Issue by junan-trustarc** [langchain-ai/langgraph#2497]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
https://github.com/langchain-ai/langgraph/blob/main/libs/sdk-js/src/client.ts#L56

I can see 0.0.26 has some additional change to use "process"
process is not available on spa without SSR. please make optional here.


0.0.25 is fine.
```

### Error Message and Stack Trace (if applicable)

```shell
core.mjs:7195 ERROR ReferenceError: process is not defined
    at _LangGraphApiService.getClient (lang-graph-api.service.ts:130:12)
    at _LangGraphApiService.<anonymous> (lang-graph-api.service.ts:62:35)
    at Generator.next (<anonymous>)
    at chunk-OWZQ6ICK.js:38:61
    at __async (chunk-OWZQ6ICK.js:22:10)
```

### Description

there is break changes in 0.0.26

### System Info

Platform (window)
Angular

**Comment by junan-trustarc** [comment]
ah... found that I can pass apiKey on creation of Client in order to avoid "process" to be called.

```
private getClient(): Client {
    return new Client({
      ...,
      apiKey: ' ',
    });
  }
```
