### ISSUE TITLE
Pydantic objects with all None properties converted to empty dict internally instead of dict with None values

### ISSUE THREAD

**Issue by majorgilles** [langchain-ai/langgraph#2538]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
from pydantic import BaseModel
from langgraph.graph import StateGraph, START, END
from langchain_core.output_parsers import PydanticOutputParser


# Define the state schema with an optional string key "foo"
class OverallState(BaseModel):
    foo: str | None  # Optional string

class InputState(BaseModel):
    bar: str | None  # Optional string

class OutputState(BaseModel):
    baz: str | None  # Optional string

# Define the node function that sets "foo" to None
def set_foo_to_none(state: InputState) -> OverallState:
    return OverallState(foo=None)

def set_baz(state: OverallState) -> OutputState:
    return OutputState(baz=state.foo)

# Build the state graph
builder = StateGraph(OverallState, input=InputState, output=OutputState)  # Initialize the graph
builder.add_node("set_foo_to_none", set_foo_to_none)  # Add the node
builder.add_node("set_baz", set_baz)  # Add the node

builder.add_edge(START, "set_foo_to_none")  # Start the graph with the node
builder.add_edge("set_foo_to_none", "set_baz")  # Connect the nodes
builder.add_edge("set_baz", END)  # End the graph after the node

# Compile the graph
graph = builder.compile()


if __name__ == "__main__":
    # Invoke the graph with an initial state
    response = graph.invoke({"bar": "initial value bar"})
    print(f"Response: " + str(response))
```

### Error Message and Stack Trace (if applicable)

```shell
Traceback (most recent call last):
  File "/Users/gillesmajor/dev/lizy-ai/projects/picture_categorization/graph_v1.py", line 38, in <module>
    response = graph.invoke({"bar": "initial value bar"})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gillesmajor/Library/Caches/pypoetry/virtualenvs/lizy-ai-4pk-LIdT-py3.12/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 1884, in invoke
    for chunk in self.stream(
                 ^^^^^^^^^^^^
  File "/Users/gillesmajor/Library/Caches/pypoetry/virtualenvs/lizy-ai-4pk-LIdT-py3.12/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 1611, in stream
    while loop.tick(input_keys=self.input_channels):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gillesmajor/Library/Caches/pypoetry/virtualenvs/lizy-ai-4pk-LIdT-py3.12/lib/python3.12/site-packages/langgraph/pregel/loop.py", line 421, in tick
    self.tasks = prepare_next_tasks(
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/gillesmajor/Library/Caches/pypoetry/virtualenvs/lizy-ai-4pk-LIdT-py3.12/lib/python3.12/site-packages/langgraph/pregel/algo.py", line 361, in prepare_next_tasks
    if task := prepare_single_task(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/gillesmajor/Library/Caches/pypoetry/virtualenvs/lizy-ai-4pk-LIdT-py3.12/lib/python3.12/site-packages/langgraph/pregel/algo.py", line 631, in prepare_single_task
    val = next(
          ^^^^^
  File "/Users/gillesmajor/Library/Caches/pypoetry/virtualenvs/lizy-ai-4pk-LIdT-py3.12/lib/python3.12/site-packages/langgraph/pregel/algo.py", line 769, in _proc_input
    val = proc.mapper(val)
          ^^^^^^^^^^^^^^^^
  File "/Users/gillesmajor/Library/Caches/pypoetry/virtualenvs/lizy-ai-4pk-LIdT-py3.12/lib/python3.12/site-packages/langgraph/graph/state.py", line 814, in _coerce_state
    return schema(**input)
           ^^^^^^^^^^^^^^^
  File "/Users/gillesmajor/Library/Caches/pypoetry/virtualenvs/lizy-ai-4pk-LIdT-py3.12/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for OverallState
foo
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
```

### Description

This bug has been confirmed by Isaac Herhenson.

Basically, internally, langgraph is converting a CertainPydanticObjetct(prop1=None, prop2=None) to '{}' (empty dict) when passing states around nodes. Instead of passing {"prop1": None, "Prop2": None}, it passes {} to the next node, leading to various internal errors in various contexts. Making nodes return a dict with `pydantic_object.model_dump()` solves the issue temporarily.

### System Info

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
awscli = "^1.36.4" # required as a normal dependency to install common at runtime
boto3 = "==1.35.63"
botocore = "==1.35.63"
bs4 = "==0.0.2"
chromadb = "==0.5.18"
langgraph = "==0.2.50"
langsmith = "==0.1.143"
langchain-community = "==0.3.7"
langchain-chroma = "==0.1.4"
langchain-core = "==0.3.19"
langchain-openai = "==0.2.8"
google-cloud-documentai = "==3.0.1"
html2text = "==2024.2.26"
phonenumberslite = "==8.12.48" # leave at this version or common will not install dynamically
pydantic = { extras = ["email"], version = "==2.9.2" }
sentry-sdk = "==2.14.0" # leave at this version or common will not install dynamically
redis = "==5.2.0"
ring = "==0.10.1"
requests = "==2.32.3"
requests-aws4auth = "==1.3.1"
setuptools = "==74.1.1" # leave at this version or common will not install dynamically
ssm-cache = "==2.10"
vininfo = "==1.8.0"

[tool.poetry.group.dev.dependencies]
boto3-stubs = "==1.35.45"
coveralls = "==4.0.1"
coverage = "==7.6.1"
mypy = "==1.12.1"
pre-commit = "==3.8.0"
pytest = "==7.4.4"
pytest-asyncio = "==0.23.7"
pytest-cov = "==5.0.0"
pytest-mock = "==3.12.0"
pytest-socket = "==0.7.0"
pytest-xdist = "==3.5.0"
types-requests = "==2.31.0.6"
types-python-dateutil = "^2.9.0.20241003"
types-pytz = "==2024.2.0.20240913"
ruff = "==0.7.0"
vulture = "==2.11"

**Comment by asleroid** [comment]
@gbaian10 do you suggest that teams working to take LangGraph to production with complex workflows should avoid using Pydantic state models?

**Comment by gbaian10** [comment]
> @gbaian10 do you suggest that teams working to take LangGraph to production with complex workflows should avoid using Pydantic state models?

In large projects, I try to avoid using Pydantic's state to prevent unexpected errors.

**Comment by asleroid** [comment]
> In large projects, I try to avoid using Pydantic's state to prevent unexpected errors.
Thanks for getting back @gbaian10, do you recommend using TypedDict then?  Using pydantic is promoted in many LangGraph videos and examples, so I am surprised by this comment.  I really appreciate your guidance.

**Comment by gbaian10** [comment]
I saw that the official examples mainly used `TypedDict`. Maybe I haven't looked at the new ones for a while?

**Comment by diego-coder** [comment]
Yeah just to confirm, however these pydantic issues are handled in the future, this specific bug has been fixed. Output is now correct ({'baz': None} instead of {} or missing fields).

**Comment by niladrighosh03** [comment]
Looking at the stack trace, the issue seems to occur during `_coerce_state`, where the input becomes `{}` before being passed into the Pydantic schema, leading to the missing field error.

This suggests that somewhere upstream the model serialization is dropping `None` fields instead of preserving them.

It might be worth checking whether `.model_dump(exclude_none=True)` (or similar behavior) is being applied unintentionally.
