### ISSUE TITLE
I want to deploy the langgraph platform on the intranet. Can I do this without entering the langsmith key?

### ISSUE THREAD

**Issue by LiChengChen666** [langchain-ai/langgraph#2549]

**Comment by vbarda** [comment]
I believe you want a self-hosted deployment (lite version) -- you still need a LangSmith key, but you can do it with a free tier. 

See more here:
https://langchain-ai.github.io/langgraph/how-tos/deploy-self-hosted/
https://langchain-ai.github.io/langgraph/concepts/#deployment-options

Does this help?

**Comment by vbarda** [comment]
can you provide the versions of the libraries you're using and the command you used to build the image?

**Comment by vbarda** [comment]
Will close this issue due to inactivity, @arisylafeta feel free to open another issue if this is still happening for you

**Comment by Jackoder** [comment]
@vbarda I'm facing the same error

```
2024-12-30T13:17:21.986841Z [info     ] Using auth of type=noop        [langgraph_api.auth.middleware] api_revision=3b943f4 api_variant=local
2024-12-30T13:17:21.987666Z [info     ] Started server process [1]     [uvicorn.error] api_revision=3b943f4 api_variant=local color_message=Started server process [%d]
2024-12-30T13:17:21.987748Z [info     ] Waiting for application startup. [uvicorn.error] api_revision=3b943f4 api_variant=local
2024-12-30T13:17:21.987885Z [warning  ] No license key found, running in test mode with LangSmith API key. For production use, set LANGGRAPH_CLOUD_LICENSE_KEY in environment. [langgraph_license.validation] api_revision=3b943f4 api_variant=local
2024-12-30T13:17:22.702202Z [info     ] HTTP Request: GET https://api.smith.langchain.com/auth?langgraph-api=true "HTTP/1.1 200 OK" [httpx] api_revision=3b943f4 api_variant=local
2024-12-30T13:17:22.862221Z [error    ] Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/api/langgraph_api/lifespan.py", line 29, in lifespan
  File "/usr/local/lib/python3.11/site-packages/langgraph_storage/database.py", line 148, in start_pool
    await migrate()
  File "/usr/local/lib/python3.11/site-packages/langgraph_storage/database.py", line 108, in migrate
    await cur.execute(stmt.strip(), prepare=False)
  File "/usr/local/lib/python3.11/site-packages/psycopg/cursor_async.py", line 97, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "thread" does not exist
```

deps：

```
pip list
Package                       Version       Editable project location
----------------------------- ------------- ---------------------------------
aiohappyeyeballs              2.3.4
aiohttp                       3.10.0
aiosignal                     1.3.1
aiosqlite                     0.20.0
annotated-types               0.7.0
anthropic                     0.42.0
anyio                         4.4.0
asyncio                       3.4.3
attrs                         23.2.0
beautifulsoup4                4.12.3
blinker                       1.9.0
bs4                           0.0.2
build                         1.2.2.post1
CacheControl                  0.14.1
certifi                       2024.7.4
cffi                          1.17.1
charset-normalizer            3.3.2
cleo                          2.1.0
click                         8.1.7
cobble                        0.1.4
colorama                      0.4.6
crashtest                     0.4.1
cryptography                  43.0.3
dataclasses-json              0.6.7
defusedxml                    0.7.1
distlib                       0.3.9
distro                        1.9.0
duckduckgo_search             7.1.1
dulwich                       0.21.7
et_xmlfile                    2.0.0
fastjsonschema                2.21.1
filelock                      3.15.4
Flask                         3.1.0
frozenlist                    1.4.1
fsspec                        2024.6.1
greenlet                      3.0.3
h11                           0.14.0
httpcore                      1.0.5
httpx                         0.27.0
httpx-sse                     0.4.0
huggingface-hub               0.24.5
idna                          3.7
importlib_metadata            8.5.0
installer                     0.7.0
itsdangerous                  2.2.0
jaraco.classes                3.4.0
Jinja2                        3.1.5
jiter                         0.5.0
jsonpatch                     1.33
jsonpointer                   3.0.0
jsonschema_rs                 0.25.1
keyring                       24.3.1
langchain                     0.3.12
langchain-anthropic           0.3.0
langchain-community           0.3.10
langchain-core                0.3.25
langchain-openai              0.2.11
langchain-text-splitters      0.3.4
langgraph                     0.2.60
langgraph-api                 0.0.14
langgraph-checkpoint          2.0.9
langgraph-checkpoint-postgres 2.0.9
langgraph-checkpoint-sqlite   2.0.1
langgraph-cli                 0.1.65
langgraph-sdk                 0.1.48
langsmith                     0.1.147
lxml                          5.3.0
mammoth                       1.8.0
markdownify                   0.14.1
markitdown                    0.0.1a3
MarkupSafe                    3.0.2
marshmallow                   3.21.3
more-itertools                10.5.0
msgpack                       1.1.0
multidict                     6.0.5
my_agent                      0.1.0         D:\AI\langgraph-example-pyproject
mypy-extensions               1.0.0
numpy                         1.26.4
openai                        1.58.1
openpyxl                      3.1.5
orjson                        3.10.6
packaging                     24.1
pandas                        2.2.3
pathvalidate                  3.2.1
pdfminer.six                  20240706
pexpect                       4.9.0
pillow                        11.0.0
pip                           24.2
pipdeptree                    2.24.0
pkginfo                       1.12.0
platformdirs                  4.3.6
poetry                        1.8.5
poetry-core                   1.9.1
poetry-plugin-export          1.8.0
primp                         0.9.2
psycopg                       3.2.3
psycopg-pool                  3.2.4
ptyprocess                    0.7.0
puremagic                     1.28
pycparser                     2.22
pydantic                      2.8.2
pydantic_core                 2.20.1
pydantic-settings             2.7.0
pydub                         0.25.1
PyJWT                         2.10.1
pyproject_hooks               1.2.0
python-dateutil               2.9.0.post0
python-docx                   1.1.2
python-dotenv                 1.0.1
python-pptx                   1.0.2
pytz                          2024.2
pywin32-ctypes                0.2.3
PyYAML                        6.0.1
RapidFuzz                     3.11.0
regex                         2024.7.24
requests                      2.32.3
requests-toolbelt             1.0.0
setuptools                    75.1.0
shellingham                   1.5.4
six                           1.17.0
sniffio                       1.3.1
soupsieve                     2.6
SpeechRecognition             3.12.0
SQLAlchemy                    2.0.31
sse-starlette                 2.1.3
starlette                     0.42.0
structlog                     24.4.0
tavily-python                 0.5.0
tenacity                      8.5.0
tiktoken                      0.7.0
tokenizers                    0.19.1
tomlkit                       0.13.2
tqdm                          4.66.4
trove-classifiers             2024.10.21.16
typing_extensions             4.12.2
typing-inspect                0.9.0
tzdata                        2024.2
urllib3                       2.2.2
uvicorn                       0.34.0
virtualenv                    20.28.0
watchfiles                    1.0.3
Werkzeug                      3.1.3
wheel                         0.44.0
XlsxWriter                    3.2.0
yarl                          1.9.4
youtube-transcript-api        0.6.3
zipp                          3.21.0
```

**Comment by lowjiansheng** [comment]
I'm facing the exact same issue when trying to run the built image.  
This is the full error stack trace that resulted in the failed authentication.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 207, in handle_async_request
    raise UnsupportedProtocol(
httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/api/langgraph_license/validation.py", line 56, in check_langsmith_access
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1768, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
```

**Comment by rushab-agi** [comment]
i am getting this on the latest version

**Comment by argemiront** [comment]
I am under the impression it is virtually impossible to fully run a langgraph server fully local with no contact with Langsmith. Docs are not clear and I faced the exact same issue, even worse, by running `langgraph dev` it is not possible to use postgres checkpoints or store. I was really enjoying langgraph until now with these limitations

**Comment by Jae-1409** [comment]
@argemiront 
You can use postgres checkpoints when running `langgraph dev`.
I'm currently using 
@langchain/core@0.3.71
@langchain/langgraph@0.4.4
@langchain/langgraph-checkpoint-postgres@0.1.2

You should modify your code of @langchain/langgraph-api/dist/storage/checkpoint.mjs, to use PostgresSaver as checkpointer!

Now I'm currently struggling with Queue Workers..

I wanna scale my langgraph-api service, but FileSystemPersistence is the main problem.

**Comment by ljxpython** [comment]
langgraph-api-1  | 2025-12-08T04:41:27.197512Z [warning  ] No enterprise license key or LangSmith API key found. To use LangGraph for development, please configure a valid LANGSMITH_API_KEY in the environment specified in your langgraph.json file. This can be done either in the .env file indicated therein or in the environment variables configured by it. [langgraph_license.validation] api_revision=f18094f api_variant=licensed langgraph_api_version=0.5.32 thread_name=MainThread
langgraph-api-1  | 2025-12-08T04:41:27.198035Z [error    ] Traceback (most recent call last):
langgraph-api-1  |   File "/usr/lib/python3.13/site-packages/starlette/routing.py", line 694, in lifespan
langgraph-api-1  |     async with self.lifespan_context(app) as maybe_state:
langgraph-api-1  |                ~~~~~~~~~~~~~~~~~~~~~^^^^^
langgraph-api-1  |   File "/usr/lib/python3.13/contextlib.py", line 214, in __aenter__
langgraph-api-1  |     return await anext(self.gen)
langgraph-api-1  |            ^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1  |   File "/usr/lib/python3.13/site-packages/langgraph_runtime_postgres/lifespan.py", line 71, in lifespan
langgraph-api-1  |     raise ValueError(
langgraph-api-1  |     ...<7 lines>...
langgraph-api-1  |     )
langgraph-api-1  | ValueError: License verification failed. Please ensure proper configuration:
langgraph-api-1  | - For local development, set a valid LANGSMITH_API_KEY for an account with LangGraph Cloud access in the environment defined in your langgraph.json file.
langgraph-api-1  | - For production, configure the LANGGRAPH_CLOUD_LICENSE_KEY environment variable with your LangGraph Cloud license key.
langgraph-api-1  | Review your configuration settings and try again. If issues persist, contact support for assistance.
 
I have the same problem in this question,I just want to devlepment self-server
