### ISSUE TITLE
Get redis key split error on official document about the RedisSaver

### ISSUE THREAD

**Issue by KanaSukita** [langchain-ai/langgraph#2712]
### Checked other resources

- [X] This is a bug, not a usage question. For questions, please use GitHub Discussions.
- [X] I added a clear and detailed title that summarizes the issue.
- [X] I read what a minimal reproducible example is (https://stackoverflow.com/help/minimal-reproducible-example).
- [X] I included a self-contained, minimal example that demonstrates the issue INCLUDING all the relevant imports. The code run AS IS to reproduce the issue.

### Example Code

```python
from configs import REDIS_CONFIG
from redis import Redis
from utils import RedisSaver
from typing_extensions import TypedDict
from langgraph.graph import StateGraph, START, END
 
memory = RedisSaver(Redis(**REDIS_CONFIG))
 
class SubState(TypedDict):
    flag: int
 
def interrupt_route(state):
    return "interrupt" if state.get("flag") == 1 else "end"
 
def p2(state):
    print("interrupt")
 
sub_workflow = StateGraph(SubState)
sub_workflow.add_node("p1", lambda state: {"flag": state.get("flag", 0) + 1})
sub_workflow.add_node("p2", p2)
sub_workflow.add_edge(START, "p1")
sub_workflow.add_conditional_edges("p1", interrupt_route, {"interrupt": "p2", "end": END})
sub_workflow.add_edge(START, "p1")
sub_workflow.add_edge("p2", "p1")
 
sub_graph = sub_workflow.compile(
    interrupt_before=[
        "p2",
    ]
)
 
config = {
    "configurable": {
        "thread_id": "123"
    }
}
 
class MainState(TypedDict):
    flag: int
 
workflow = StateGraph(MainState)
workflow.add_node("sub_graph", sub_graph)
workflow.add_edge(START, "sub_graph")
workflow.add_edge("sub_graph", END)
graph = workflow.compile(checkpointer=memory)
 
for event, chunk in graph.stream({"flag": 0}, config, stream_mode=["updates", "messages"]):
    print(event, chunk)
 
graph.get_state(config, subgraphs=True)
```

### Error Message and Stack Trace (if applicable)

```shell
2024-12-11 10:43:52,580 DEBUG [MainProcess.1458:Thread-3 (process_message).140583974635264] [/home/langgraph-redis/kafka_server.py:124] [STAT] {"logEvent": "updateState", "dialogId": "464bda98-c076-4a7b-85cc-d07416d01d53", "requestId": "dda1821b-57e2-4f11-a07f-b5be95b09e5b", "logMessage": "{\"__interrupt__\": []}"}
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
['checkpoint', '464bda98-c076-4a7b-85cc-d07416d01d53', '', '1efb7acc-e6cc-667d-8000-4da30d12e037']
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
['checkpoint', '464bda98-c076-4a7b-85cc-d07416d01d53', '', '1efb7acc-f6cc-6860-8002-8ec69e580160']
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
['checkpoint', '464bda98-c076-4a7b-85cc-d07416d01d53', '', '1efb7acc-e6c7-6765-bfff-0b921ffdfbd4']
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
['checkpoint', '464bda98-c076-4a7b-85cc-d07416d01d53', '', '1efb7acc-e935-66ed-8001-078671ffd609']
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
['checkpoint', '464bda98-c076-4a7b-85cc-d07416d01d53', '', '1efb7acc-f6cc-6860-8002-8ec69e580160']
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
['checkpoint', '464bda98-c076-4a7b-85cc-d07416d01d53', '', '1efb7acc-f6cc-6860-8002-8ec69e580160']
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
['checkpoint', '464bda98-c076-4a7b-85cc-d07416d01d53', 'automation', 'd3048595-0167-ff1c-cfca-47e61b889371', '1efb7acd-01d7-6eb7-8001-42a027e47c5f']
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
['checkpoint', '464bda98-c076-4a7b-85cc-d07416d01d53', '', '1efb7acc-e6cc-667d-8000-4da30d12e037']
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
['checkpoint', '464bda98-c076-4a7b-85cc-d07416d01d53', '', '1efb7acc-f6cc-6860-8002-8ec69e580160']
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
['checkpoint', '464bda98-c076-4a7b-85cc-d07416d01d53', '', '1efb7acc-e6c7-6765-bfff-0b921ffdfbd4']
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
['checkpoint', '464bda98-c076-4a7b-85cc-d07416d01d53', '', '1efb7acc-e935-66ed-8001-078671ffd609']
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
['checkpoint', '464bda98-c076-4a7b-85cc-d07416d01d53', '', '1efb7acc-f6cc-6860-8002-8ec69e580160']
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
['checkpoint', '464bda98-c076-4a7b-85cc-d07416d01d53', '', '1efb7acc-f6cc-6860-8002-8ec69e580160']
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
['checkpoint', '464bda98-c076-4a7b-85cc-d07416d01d53', 'automation', 'd3048595-0167-ff1c-cfca-47e61b889371', '1efb7acd-01d7-6eb7-8001-42a027e47c5f']
Exception in thread Thread-3 (process_message):
Traceback (most recent call last):
  File "/home/langgraph-redis/kafka_server.py", line 243, in process_message
    {"logEvent": "finishState", "dialogId": dialog_id, "requestId": request_id, "logMessage": jsonify_log({"messages": copilot.get_state(config, subgraphs=True).values.get("messages", [])})}))
                                                                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/py311/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 640, in get_state
    return self._prepare_state_snapshot(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/py311/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 503, in _prepare_state_snapshot
    task_states[task.id] = subgraphs[task.name].get_state(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/py311/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 639, in get_state
    saved = checkpointer.get_tuple(config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/langgraph-redis/utils/checkpointers.py", line 293, in get_tuple
    checkpoint_key = self._get_checkpoint_key(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/langgraph-redis/utils/checkpointers.py", line 371, in _get_checkpoint_key
    latest_key = max(
                 ^^^^
  File "/home/langgraph-redis/utils/checkpointers.py", line 373, in <lambda>
    key=lambda k: _parse_redis_checkpoint_key(k.decode())[
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/langgraph-redis/utils/checkpointers.py", line 64, in _parse_redis_checkpoint_key
    namespace, thread_id, checkpoint_ns, checkpoint_id = redis_key.split(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 4)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py311/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/anaconda3/envs/py311/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/langgraph-redis/kafka_server.py", line 254, in process_message
    {"logEvent": "finishState", "dialogId": dialog_id, "requestId": request_id, "logMessage": jsonify_log({"messages": copilot.get_state(config, subgraphs=True).values.get("messages", [])})}))
                                                                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/py311/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 640, in get_state
    return self._prepare_state_snapshot(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/py311/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 503, in _prepare_state_snapshot
    task_states[task.id] = subgraphs[task.name].get_state(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/py311/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 639, in get_state
    saved = checkpointer.get_tuple(config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/langgraph-redis/utils/checkpointers.py", line 293, in get_tuple
    checkpoint_key = self._get_checkpoint_key(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/langgraph-redis/utils/checkpointers.py", line 371, in _get_checkpoint_key
    latest_key = max(
                 ^^^^
  File "/home/langgraph-redis/utils/checkpointers.py", line 373, in <lambda>
    key=lambda k: _parse_redis_checkpoint_key(k.decode())[
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/langgraph-redis/utils/checkpointers.py", line 64, in _parse_redis_checkpoint_key
    namespace, thread_id, checkpoint_ns, checkpoint_id = redis_key.split(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 4)
```

### Description

I got errors when using the RedisSaver from the official how-to guide from https://langchain-ai.github.io/langgraph/how-tos/persistence_redis/

I create a subgraph and set interrupt_node in it. When I trigger the interrupt node in the subgraph, I want to get the state with subgraphs and I got 5 splits on the redis_key, that's why I got the error. 

Any fix solutions for the official RedisSaver?

### System Info

langgraph==0.2.45

**Comment by vbarda** [comment]
Thanks for reporting! Should be fixed now
