### ISSUE TITLE
get_graph(xray=True). ValueError: Node with id condition already exists

### ISSUE THREAD

**Issue by mrbuslov** [langchain-ai/langgraph#309]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```
from PIL import Image as PIL_Image

...
image = PIL_Image.open(
        io.BytesIO(
            graph.compile()
            .get_graph(xray=True)
            # .get_graph()
            .draw_png()
        )
    )
    image.show()
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/home/dmitry/builder.py", line 143, in <module>
    .get_graph(xray=True)
     ^^^^^^^^^^^^^^^^^^^^
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/langgraph/graph/graph.py", line 336, in get_graph
    node.get_graph(config=config, xray=xray)
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/langgraph/graph/graph.py", line 358, in get_graph
    cond = graph.add_node(branch.condition, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/langchain_core/runnables/graph.py", line 209, in add_node
    raise ValueError(f"Node with id {id} already exists")
ValueError: Node with id condition already exists
```

### Description

Hello, guys! I receive this error on langgraph version == 0.0.37. When i call get_graph(x_ray=_**False**_), no error occures. But I need x_ray, because every node from edges below is subgraph.
Edges:
`{('__start__', 'user_message'), ('task_1-step_1', '__end__'), ('user_message', 'task_3-step_1'), ('task_2-step_1', '__end__'), ('task_5-step_1', '__end__'), ('task_6-step_1', '__end__'), ('user_message', 'task_2-step_1'), ('user_message', 'task_5-step_1'), ('user_message', 'task_6-step_1'), ('user_message', 'task_4-step_1'), ('user_message', 'task_1-step_1'), ('task_3-step_1', '__end__'), ('task_4-step_1', '__end__')}`
Error `ValueError: Node with id condition already exists` still occures

I downgraded to langgraph version == 0.0.36 and this error occures. So downgrading didn't solve the issue.

```
Traceback (most recent call last):
  File "/home/dmitry/builder.py", line 143, in <module>
    .get_graph(xray=True)
     ^^^^^^^^^^^^^^^^^^^^
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/langgraph/graph/graph.py", line 355, in get_graph
    graph.add_edge(start_nodes[start], end_nodes[end])
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/langchain_core/runnables/graph.py", line 227, in add_edge
    if target.id not in self.nodes:
       ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
```

### System Info

langgraph == 0.0.37

**Comment by nfcampos** [comment]
if you update to latest version this should be fixed.
