### ISSUE TITLE
Unable to define a conditional edge

### ISSUE THREAD

**Issue by jindalAnuj** [langchain-ai/langgraph#413]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```
    class WorkFlow():
	def __init__(self):
		nodes = Nodes()
		workflow = StateGraph(PersonState)
		workflow.add_node("userInput", nodes.userInput)
		workflow.add_node("text2PersonInfo", nodes.text2PersonInfo)
		workflow.add_node("personInfoValidate", nodes.personInfoValidate)
		workflow.add_node("missingDataAgent", nodes.missingDataAgent)
		workflow.set_entry_point("userInput")
		workflow.add_edge('userInput', 'text2PersonInfo')
		workflow.add_edge('text2PersonInfo', 'personInfoValidate')
		workflow.add_conditional_edges(
			"personInfoValidate",
			nodes.personInfoValidate,
			{
				"incomplete": "missingDataAgent",
				"end": END
			}
		)
		self.app = workflow.compile()


```

```
 Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jindal/AppDevelopment/30DaysofAI/LLMHandsOn/lang_graph/main.py", line 15, in <module>
    app.invoke({})
  File "/Users/jindal/Library/Caches/pypoetry/virtualenvs/llm-handson-m_vF4p_v-py3.10/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 1171, in invoke
    for chunk in self.stream(
  File "/Users/jindal/Library/Caches/pypoetry/virtualenvs/llm-handson-m_vF4p_v-py3.10/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 774, in stream
    _panic_or_proceed(done, inflight, step)
  File "/Users/jindal/Library/Caches/pypoetry/virtualenvs/llm-handson-m_vF4p_v-py3.10/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 1260, in _panic_or_proceed
    raise exc
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/jindal/Library/Caches/pypoetry/virtualenvs/llm-handson-m_vF4p_v-py3.10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2499, in invoke
    input = step.invoke(
  File "/Users/jindal/Library/Caches/pypoetry/virtualenvs/llm-handson-m_vF4p_v-py3.10/lib/python3.10/site-packages/langgraph/utils.py", line 88, in invoke
    ret = context.run(self.func, input, **kwargs)
  File "/Users/jindal/Library/Caches/pypoetry/virtualenvs/llm-handson-m_vF4p_v-py3.10/lib/python3.10/site-packages/langgraph/graph/graph.py", line 74, in _route
    destinations = [self.ends[r] for r in result]
  File "/Users/jindal/Library/Caches/pypoetry/virtualenvs/llm-handson-m_vF4p_v-py3.10/lib/python3.10/site-packages/langgraph/graph/graph.py", line 74, in <listcomp>
    destinations = [self.ends[r] for r in result]
TypeError: unhashable type: 'dict'
```

```
[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
ollama = "^0.1.8"
load-dotenv = "^0.1.0"
langgraph = "0.0.45"
langchain = "^0.1.17"
```

### Description

whenever i remove conditional node it works fine

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103
> Python Version:  3.10.14 (main, Mar 19 2024, 21:46:16) [Clang 15.0.0 (clang-1500.1.0.2.5)]

Package Information
-------------------
> langchain_core: 0.1.52
> langchain: 0.1.17
> langchain_community: 0.0.37
> langsmith: 0.1.54
> langchain_openai: 0.0.5
> langchain_text_splitters: 0.0.1
> langgraph: 0.0.45

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langserve

**Comment by hinthornw** [comment]
What does `personInfoValidate` look like?

**Comment by jindalAnuj** [comment]
` def personInfoValidate(self, state):
        ask_for = []
        status = "end"
        print('personInfoValidate',state)
        # Check if fields are empty 
        # for field, value in state["person"].dict().items():
        #     if value in [None, "", 0]:  # You can add other 'empty' conditions as per your requirements
        #         print(f"Field '{field}' is empty.")
        #         ask_for.append(f'{field}')
        # if ask_for:
        #     status = "incomplete"
        return {
            **state,
            "status": status,
            # "ask_for": ask_for
        }`
        
        
some commented code for testing

**Comment by dylanlap98** [comment]
I'm having this same problem.  


Pip versions:
...
langgraph 0.0.46
langchain-core 0.1.52
...

Code:

```

from langgraph.graph import StateGraph, END
from typing import TypedDict, Annotated
 
class GraphState(TypedDict):
    num_steps: int
    email: str
    classification: str
    technology: str
 
def graph_printer(state):
    print("-- GRAPH PRINTER --")
    print(f"classification: {state['classification']}")
    print(f"technology: {state['technology']}")
    print(f"num_steps: {state['num_steps']}")
    print()
    return
 
def router_1(state):    #: List[BaseMessage]
    #technology = state['technology']
 
    ## LLM call would go here (for now simulate response):
    technology = "Sagemaker"
 
    print(technology)
    if 'aws' in technology.lower():
        print("RUNNING AWS\n")
        return "aws"
        #return {"technology": "aws"} # trying other formats to fix
    else:
        print("RUNNING OTHER\n")
        return "other"
        #return {"technology": "other"}
        #return {"input": "other"}
 
def lane_switch(state):
    print(" --- RAN LANE SWITCH --- ")
    print()
    return
   
testgraph = StateGraph(GraphState)
 
testgraph.add_node("state_printer_1", graph_printer)
testgraph.add_node("router", router_1)
testgraph.add_node("state_printer_2", graph_printer)
testgraph.add_node("lane_switcher", lane_switch) # only run if aws
testgraph.set_entry_point("state_printer_1")
testgraph.add_edge("state_printer_1", "router")
testgraph.add_conditional_edges(
    "router",
    router_1,
    {
        "aws": "lane_switcher",
        "other": "state_printer_2"
    }
)
testgraph.add_edge("lane_switcher", "state_printer_2")
testgraph.add_edge("state_printer_2", END)
 

testapp = testgraph.compile()
 
email  = "HELLO THERE AWS USER! Thanks." # simulate email
inputs = {"email": email, "num_steps": 0}
testapp.invoke(inputs)

```

Output error:

langgraph.errors.InvalidUpdateError: Expected dict, got other


Hoping this example helps..
-Dylan LaPierre

**Comment by DevTimBo** [comment]
I had the same problem you can fix this by adding a additional state to ur stategraph that contains the next_step

See my example:
`class GraphState(TypedDict):
    question : str
    generation : str
    context : str
    next_step: str

def generate(state):
    print("Step: Generating Final Response")
    question = state["question"]
    context = state["context"]
    generation = generate_chain.invoke({"context": context, "question": question})
    return {"generation": generation}

def document_search(state):
    search_query = state['question']
    print(f'Step: Searching the Documents for: "{search_query}"')
    search_result = search_document_tool.invoke(search_query)
    return {"context": search_result}


def route_question(state):
    print("Step: Routing Query")
    question = state['question']
    
    if not "context" in state:
        state['context'] = ""
    context = state['context']
    
    output = question_router.invoke({"question": question,"context": context})
    if output['choice'] == "document_search":
        print("Step: Routing Query to Document Search")
        return {"next_step": "document_search"}
    elif output['choice'] == 'generate':
        print("Step: Routing Query to Generation")
        return {"next_step": "generate"}
    
def decide_to_finish(state):
    if state["next_step"] == "document_search":
        return "document_search"
    elif state["next_step"] == "generate":
        return "generate"`
        
       `workflow = StateGraph(GraphState)
workflow.add_node("route_question", route_question)
workflow.add_node("document_search", document_search)
workflow.add_node("generate", generate)

workflow.set_entry_point("route_question")
workflow.add_edge("document_search", "route_question")
workflow.add_edge("generate", END)
workflow.add_conditional_edges(
    "route_question",
    decide_to_finish,
    {
        "document_search": "document_search",
        "generate": "generate",
    }
)
local_agent = workflow.compile()`

I hope this helps.

**Comment by DevTimBo** [comment]
You can fix this by adding a next_step to your graph instead of just passing the route function to the conditional edge
![image](https://github.com/langchain-ai/langgraph/assets/141731371/ab2f6373-0a91-416f-b1eb-614c81389d17)

![image](https://github.com/langchain-ai/langgraph/assets/141731371/5a0043b2-79a1-48c5-ac59-737da307c00e)

I hope this helps
