### ISSUE TITLE
Langraph Agent, Code works with OpenAI, but throws an error with Claude: (ValueError: System message must be at the beginning of the message list.)

### ISSUE THREAD

**Issue by Merlinvt** [langchain-ai/langgraph#982]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_chroma import Chroma
from langgraph.prebuilt import ToolNode
from langgraph.checkpoint import MemorySaver
from langgraph.graph import StateGraph, MessagesState
from langgraph.checkpoint import MemorySaver

import os
from dotenv import load_dotenv
from typing import Literal
from langchain_anthropic import ChatAnthropic


# Import LangSmith tracer
from langchain.callbacks.tracers.langchain import LangChainTracer

# Import tools from todo_tools.py
from todo_tools import (
    read_first_inbox_item, delete_inbox_item, read_tasks, read_inbox, read_projects,
    read_task, read_project, create_task, create_project, create_inbox_item,
    update_tasks, update_project, reinitialize_database, starting_context
)


# Function to create and compile the bot
def create_todo_agent(channelid: str):
    system_massage = f"""You are an assistant that manages tasks, projects, and task inboxes.
    Use the provided tool to get the job done. Whenever a tool asks for a channel ID, the channel ID is '{channelid}'.
    Help the user with their Getting Things Done (GTD) workflow. In GTD, you first collect stuff in the inbox bucket. 
    It includes everything from a URL to a thought to a task like "do taxes."
    When a user gives you some input that you can't quite understand, put it as-is into the inbox using the inbox tool.
    It can be anything from just a URL to instructions, to buy food, to call XYZ.
    At some point, when the user asks you to, you will help process the inbox. 
    To do this, get the first item from the inbox and ask the user what it is. Request context from the user. 
    They need to determine whether it has multiple steps, in which case it is a project. 
    Add it to projects using the tool and create a first next action, 
    adding it as a task connected to the project by ID (you get the ID after creating the project).
    If it is a single action, create a task directly. It should be a next action. 
    Only once the inbox item is processed and added to tasks, should you delete it (with delete_inbox_item). 
    Continue processing new inbox items until the user tells you to stop.
    At a different time, the user will want to get something done. Get the starting context first, then help them pick a task. 
    Be helpful and supportive. Once the task or project is done, mark the status as "done" and "completed" as true. 
    You can do this with the update tools. Whenever a tool asks for a channel ID, the channel ID is '{channelid}'.
    """

    # Load environment variables from .env file
    load_dotenv()

    # Retrieve the API key from environment variables
    api_key = os.getenv("OPENAI_API_KEY")   
    api_key = os.getenv("ANTHROPIC_API_KEY")   

    # Define a flag to control tracing
    ENABLE_TRACING = os.getenv("LANGCHAIN_TRACING_V2") == "false"

    # Initialize LangSmith tracer conditionally
    callbacks = []
    if ENABLE_TRACING:
        tracer = LangChainTracer()
        callbacks.append(tracer)
 

    model = ChatAnthropic(model='claude-3.5-sonnet', api_key=api_key, callbacks=callbacks)
    #model = ChatOpenAI(model="gpt-4o", api_key=api_key, callbacks=callbacks)

    #db = Chroma(persist_directory="./chroma_db", embedding_function=OpenAIEmbeddings())

    # Add imported tools to the tools list
    tools = [
        read_first_inbox_item, delete_inbox_item, read_tasks,
        read_inbox, read_projects, read_task, read_project, create_task, create_project,
        create_inbox_item, update_tasks, update_project, reinitialize_database,
        starting_context
    ]

    # Bind tools to the model
    tool_node = ToolNode(tools)
    model = model.bind_tools(tools)

    def initialize_system_prompt(state: MessagesState, channelid: str):

        system_message = {
            "role": "system",
            "content": system_massage
        }
        state["messages"].append(system_message)
        return state


    def invoke_starting_context(state: MessagesState, channelid: str):
        context = starting_context.invoke({"channelid": channelid})  # Ensure the correct field name is used
        # Ensure the response contains 'role' and 'content' keys
        if isinstance(context, dict) and 'role' in context and 'content' in context:
            formatted_context = context
        else:
            formatted_context = {
                "role": "system",  # or another appropriate role
                "content": str(context)  # Convert context to string if it's not already
            }
        return {"messages": [formatted_context]}


    def should_continue(state: MessagesState) -> Literal["action", "__end__"]:
        """Return the next node to execute."""
        last_message = state["messages"][-1]
        # If there is no function call, then we finish
        if not last_message.tool_calls:
            return "__end__"
        # Otherwise if there is, we continue
        return "action"

    # Define the function that calls the model
    def call_model(state: MessagesState):
        messages = filter_messages(state["messages"])
        response = model.invoke(messages)
        # We return a list, because this will get added to the existing list
        return {"messages": response}

    def filter_messages(messages: list):
        # This is a simple helper function which only ever uses the last six messages
        if len(messages) > 6:
            return messages[-6:]
        else:
            return messages
    
    # Create the graph
    workflow = StateGraph(MessagesState)

    # Add the system prompt initialization node
    workflow.add_node("initialize_system_prompt", lambda state: initialize_system_prompt(state, channelid))

    # Define the two nodes we will cycle between
    workflow.add_node("agent", call_model)
    workflow.add_node("action", tool_node)

    workflow.set_entry_point("initialize_system_prompt")
    # Set the entry point as `initialize_system_prompt`

    # Connect the initialization node to the agent node
    workflow.add_edge("initialize_system_prompt", "agent")

    # We now add a conditional edge
    workflow.add_conditional_edges(
        "agent",
        should_continue,
    )

    # We now add a normal edge from `tools` to `agent`.
    workflow.add_edge("action", "agent")
    # Initialize memory to persist state between graph runs
    checkpointer = MemorySaver()

    # Compile the graph
    app = workflow.compile(checkpointer=checkpointer)
    return app
```

### Error Message and Stack Trace (if applicable)

```shell
Traceback (most recent call last):
  File "C:\Users\merli\Development\Python\assistant\lg.py", line 176, in <module>
    messages = app.invoke({"messages": [("human", query)]}, config={"configurable": {"thread_id": "your_thread_id"}})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\merli\miniconda3\envs\assistant\Lib\site-packages\langgraph\pregel\__init__.py", line 1554, in invoke
    for chunk in self.stream(
  File "C:\Users\merli\miniconda3\envs\assistant\Lib\site-packages\langgraph\pregel\__init__.py", line 1073, in stream
    _panic_or_proceed(done, inflight, step)
  File "C:\Users\merli\miniconda3\envs\assistant\Lib\site-packages\langgraph\pregel\__init__.py", line 1643, in _panic_or_proceed
    raise exc
  File "C:\Users\merli\miniconda3\envs\assistant\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\merli\miniconda3\envs\assistant\Lib\site-packages\langgraph\pregel\retry.py", line 72, in run_with_retry
    task.proc.invoke(task.input, task.config)
  File "C:\Users\merli\miniconda3\envs\assistant\Lib\site-packages\langchain_core\runnables\base.py", line 2497, in invoke
    input = step.invoke(input, config, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\merli\miniconda3\envs\assistant\Lib\site-packages\langgraph\utils.py", line 95, in invoke
    ret = context.run(self.func, input, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\merli\Development\Python\assistant\lg.py", line 129, in call_model
    response = model.invoke(messages)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\merli\miniconda3\envs\assistant\Lib\site-packages\langchain_core\runnables\base.py", line 4580, in invoke
    return self.bound.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\merli\miniconda3\envs\assistant\Lib\site-packages\langchain_core\language_models\chat_models.py", line 280, in invoke
    self.generate_prompt(
  File "C:\Users\merli\miniconda3\envs\assistant\Lib\site-packages\langchain_core\language_models\chat_models.py", line 713, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\merli\miniconda3\envs\assistant\Lib\site-packages\langchain_core\language_models\chat_models.py", line 570, in generate
    raise e
  File "C:\Users\merli\miniconda3\envs\assistant\Lib\site-packages\langchain_core\language_models\chat_models.py", line 560, in generate
    self._generate_with_cache(
  File "C:\Users\merli\miniconda3\envs\assistant\Lib\site-packages\langchain_core\language_models\chat_models.py", line 785, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "C:\Users\merli\miniconda3\envs\assistant\Lib\site-packages\langchain_anthropic\chat_models.py", line 755, in _generate
    payload = self._get_request_payload(messages, stop=stop, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\merli\miniconda3\envs\assistant\Lib\site-packages\langchain_anthropic\chat_models.py", line 647, in _get_request_payload
    system, formatted_messages = _format_messages(messages)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\merli\miniconda3\envs\assistant\Lib\site-packages\langchain_anthropic\chat_models.py", line 161, in _format_messages
    raise ValueError("System message must be at beginning of message list.")
ValueError: System message must be at beginning of message list.
```

### Description

I have code for an agent that I have written. It worked fine when I used OpenAI models. But the same code, with Anthropic, throws an error. The OpenAI model is commented out. If I uncomment it and comment out Claude, it's working.

Seems to be the same or related to #656 [https://github.com/langchain-ai/langchain/issues/20835] [https://github.com/langchain-ai/langchain/issues/18909] [https://github.com/promptengineers-ai/llm-server/issues/21]

Could be duplicated ? 

### System Info

langchain==0.2.7
langchain-anthropic==0.1.19
langchain-chroma==0.1.2
langchain-community==0.2.7
langchain-core==0.2.12
langchain-google-genai==1.0.7
langchain-openai==0.1.14
langchain-text-splitters==0.2.2

Platform: Windows

Python 3.11.9

**Comment by hwchase17** [comment]
different LLM providers have different message requirements. in this case, anthropic requires that system messages go at the beginning of the list of messages. the current prompting being done puts a system message not at the start. not sure whether this is intentional or not, but either way in order to get it to work with anthropic you will need to change that

**Comment by Merlinvt** [comment]
If anyone else wants to get it to work with claude:

`def call_model(state: MessagesState):

    messages = move_system_message(state["messages"])
    response = model.invoke(messages)
    return {"messages": response}

def move_system_message(messages: list):

    arbitrary_system_message = None
    non_system_messages = []

    for message in messages:
        if isinstance(message, SystemMessage) and arbitrary_system_message is None:
            arbitrary_system_message = message
        elif not isinstance(message, SystemMessage):
            non_system_messages.append(message)

    result = []
    if arbitrary_system_message:
        result.append(arbitrary_system_message)
    result.extend(non_system_messages)

    return result

workflow.add_node("agent", call_model)`

**Comment by t-tauri99** [comment]
> If anyone else wants to get it to work with claude:
> 
> `def call_model(state: MessagesState):
> 
> ```
> messages = move_system_message(state["messages"])
> response = model.invoke(messages)
> return {"messages": response}
> ```
> 
> def move_system_message(messages: list):
> 
> ```
> arbitrary_system_message = None
> non_system_messages = []
> 
> for message in messages:
>     if isinstance(message, SystemMessage) and arbitrary_system_message is None:
>         arbitrary_system_message = message
>     elif not isinstance(message, SystemMessage):
>         non_system_messages.append(message)
> 
> result = []
> if arbitrary_system_message:
>     result.append(arbitrary_system_message)
> result.extend(non_system_messages)
> 
> return result
> ```
> 
> workflow.add_node("agent", call_model)`

this was helpful. thank you
